### ISSUE TITLE
Rename repo?

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#1]
This might be a stupid question, but could you rename the repository to kimai2-docker?
The naming is a bit misleading and forking it creates a repository called **kimai2-1**, at least if someone already has Kimai2 cloned.

**Comment by tobybatch** [comment]
I totally agree with you but if i do i can't get an auto build on docker hub called kimai2.

It defaults to the repo name and I can't override if I want the auto build tag.  I could drop the 2 and just use kimai.

**Comment by kevinpapst** [comment]
Hm, thats a good argument and a ptty that they don't allow to change the image name.
Dropping the "2" would be more confusing, so we gonna stick with it for now!
