### ISSUE TITLE
Database password needs to be url encoded (prod docker)

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#10]
I had that problem now a coupe of times and sooner or later it will rise here as well:
if the database passwords contains special character like `/`, `\` or `@` Kimai will not work, as the `DATABASE_URL` is then invalid / can't be parsed by Doctrine.

So you might want to adjust that in the startup.sh

And while you are on it, I saw that you are using both `/opt/kimai/` and `/var/www/html/` in the startup.sh script. I guess its a symlink, but that maybe confusing to others.

**Comment by tobybatch** [comment]
I've fixed the symlink thing.  I'm going to add a big note about URL safe passwords.  I won't fix it now.
