### ISSUE TITLE
[BUG] entrypoints.json missing invoice key

### ISSUE THREAD

**Issue by heeen** [tobybatch/kimai2#105]
**Describe the bug**
I built a master image like this bin/build.sh -k -t Europe/Berlin -b fpm-alpine -s prod master
and in the reuslting image, entrypoints.json is missing invoice keys, resulting in an error message when trying to render templates. I would like to understand what is causing the changes to this file.

```

bash-5.0# git status | grep modified
        modified:   composer.json
        modified:   composer.lock
        modified:   public/build/entrypoints.json
        modified:   public/build/manifest.json
        modified:   public/index.php
        modified:   symfony.lock
        modified:   var/data/kimai_test.sqlite

```

some of these are obvious, like sqlite or lock files, other I don't understand why they are changed.

**To Reproduce**
Steps to reproduce the behaviour:
run build.sh for master. run containers with docker-compose up -d
enter shell in container, install git check diff

**Desktop (please complete the following information):**
 - OS: ubuntu 18
 - Docker version: 19.03.5
 - Docker compose version: 1.25.1-rc1

**docker-compose**
```
-    image: kimai/kimai2:fpm-alpine-1.5-prod
+    image: kimai/kimai2:fpm-alpine-master-prod

```
and passwords, domains changed

**Comment by tobybatch** [comment]
@heeen The master image is built against the latest commit to the base kimai repo, https://github.com/kevinpapst/kimai2

This means it may not be release stable and I'm guessing this is a bug in the kimai app.  Can you try with a numbered release please?

**Comment by kevinpapst** [comment]
Toby, pretty sure that this is not the case. 
See here: https://github.com/kevinpapst/kimai2/blob/master/public/build/entrypoints.json#L14

The files are modified: any explanation for that? 
I understand composer.json/lock/symfony.lock (thats becuase of prestissimo - which should IMO be removed btw. - and the ldap package). 
But the changes to the the other files don't make a lot of sense to me.

**Comment by tobybatch** [comment]
@kevinpapst Thanks.  I'm in the dockerfile to look at the memory limit bug, I'll try and see why that's changed.

**Comment by heeen** [comment]
How can I make sure I clean all intermediate images/volumes other stuff (except the database with my data in it) to make sure I start from a clean slate? Sorry if this is a docker newbie question.

**Comment by tobybatch** [comment]
@kevinpapst We don't knowingly change those files, they are not referenced in the project:

```bash
tobias@tobias:dockers (107-increase-dev-memory) $ grep -r entrypoints.json .
tobias@tobias:dockers (107-increase-dev-memory) $ grep -r .json .
./.git/hooks/fsmonitor-watchman.sample:	my $json_pkg;
./.git/hooks/fsmonitor-watchman.sample:		$json_pkg = "JSON::XS";
./.git/hooks/fsmonitor-watchman.sample:		$json_pkg = "JSON::PP";
./.git/hooks/fsmonitor-watchman.sample:	my $o = $json_pkg->new->utf8->decode($response);
```

Do you know what else could alter them?

**Comment by tobybatch** [comment]
@heeen  You won't need to.  Unless your kimai root folder is mounted in a volume it will not survive a rebuild/restart

**Comment by heeen** [comment]
@tobybatch can you reproduce the issue on your end? or is it some weird issue on my system? if you install git in the fpm-alpine-master-prod image and check the status of /opt/kimai, is it clean and shows the latest master commit?

**Comment by kevinpapst** [comment]
entrypoints.json is only changed if you run `npm run prod` or `yarn run prod`

**Comment by heeen** [comment]
alternatively, can I find out which RUN step in the docker file caused a file to change? If I undertsand it correctly, each RUN command causes a new image to be created which is why many people chain commands with ; or &&

**Comment by heeen** [comment]
here's the diff I am seeing except for the deleted tests folder: https://github.com/kevinpapst/kimai2/files/4449919/weird.diff.txt

**Comment by heeen** [comment]
I just ran the build script on my laptop where I didn't even have docker installed prior and got a much more plausible result:
```
bash-5.0# git status | grep modified
        modified:   composer.json
        modified:   composer.lock
        modified:   symfony.lock

```

so this seems to be related to my server environment. any idea whats going on?

**Comment by heeen** [comment]
I did a compose down and up and it seems to be resolved. could an open interactive bash instance have caused the issue? or forgetting to down before doing up again?

**Comment by vanitasvitae** [comment]
I'm chiming in to let you know that I just had the same issue.
I'm running kimai2 via docker-compose based on this [documentation](https://tobybatch.github.io/kimai2/docker-compose.html#docker-compose). I'm running in the prod configuration.

My public/build/entrypoints.json file was suddenly missing the invoices entry.
Not sure how this happened, as I didn't knowingly mess around with the deployment.

I fixed the problem by following the manual upgrade instructions mentioned [here](https://tobybatch.github.io/kimai2/updating.html#the-fpm-image).
