### ISSUE TITLE
[BUG] API Timesheet GET request begin end parameters are ignored

### ISSUE THREAD

**Issue by rpelletierrefocus** [tobybatch/kimai2#110]
Describe the bug
When I run an API Get request using the below parameters, no matter what I put in for begin end gives me all the results for that customer. Not just in between the two dates.
Running the following in jQuery, also tested with the same exact results in Postman. I have updated to the latest code here. This works as expected on the kimai demo page.

```
var settings = {
				  "url": "https://kimai.domain.com/api/timesheets?user=2&customer=1&begin=2020-04-01T14:00:00&end=2020-04-17T16:49:16",
				  "method": "GET",
				  "timeout": 0,
				  "headers": {
					"X-AUTH-TOKEN": "API_KEY",
					"Content-Type": "application/json",
					"X-AUTH-USER": "API_USER"
				  },
				};

				$.ajax(settings).done(function (response) {
				  console.log(response);
				});
                return false;
Desktop/Smartphone
Please complete the following information if this seems to be a frontend issue:
```
Device: PC
OS: Windows 10
Browser Chrome
Version 80.0.3987.163

**Comment by tobybatch** [comment]
I think this will be an issue with your nginx set up.  If nginx is not set up to forward http params it will not pass those get params.

Can you please include your nginx config?
