### ISSUE TITLE
[BUG] docker-compose throws error

### ISSUE THREAD

**Issue by airdogvan** [tobybatch/kimai2#113]
After running docker-compose build

then

docker-compose up 

it get this error

ERROR: for kimai2_nginx_1  Cannot start service nginx: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/xxx/kimai2/nginx_site.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/d5813145235b6d5a792b06a3db81ed87151ef13e05e5805d5addafe0c934c041/merged\\\" at \\\"/var/lib/docker/overlay2/d5813145235b6d5a792b06a3db81ed87151ef13e05e5805d5addafe0c934c041/merged/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

I double checked and the directory ngnix_site.conf dir is there in the pwd, meaning the directory from which I issue the docker-compose.

Any help appreciated.

**Comment by kevinpapst** [comment]
See https://github.com/tobybatch/kimai2/pull/112 and https://github.com/tobybatch/kimai2/issues/111

**Comment by tobybatch** [comment]
Yep, can you try a pull on master and retry please?

**Comment by airdogvan** [comment]
thank you, that worked for me.
Please note I had to comment out the following lines:
     start_period: 10s
      timeout: 10s
      retries: 3
as they were throwing errors.
Running Ubuntu 18.04 LTS
docker version: Docker version 19.03.6

Maybe also in the docs indicate that the trustedhost value has to be changed to the ip (or FQDN if available) of the host for it to work otherwise the web page displays a long message basically saying untrusted host.
Thanks again

**Comment by Schrolli91** [comment]
![image](https://user-images.githubusercontent.com/6043382/79945350-da7abd00-846d-11ea-8d21-6a0d269a262f.png)
> https://docs.docker.com/compose/compose-file/

**Comment by airdogvan** [comment]
thanks I'm a long way, back  version 1.17.1 here.

But it still works fine without it.
Thanks again.
