### ISSUE TITLE
docker installation kimai2:  Invalid configuration for path "kimai.data_dir"

### ISSUE THREAD

**Issue by mh33dev** [tobybatch/kimai2#118]
Steps to reproduce the behaviour:
1) Fresh Ubuntu 20.04 with Docker version 19.03.8, docker-compose version 1.25.0,
2) Install using a modified docker-compose.yml (mounting the volumes locally) for 
mysql
`volumes:
   - ./db:/var/lib/mysql`
nginx
` volumes:
      - ./kimai2/compose/nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/opt/kimai/public:ro
`
kimai
` volumes:
      - ./public:/opt/kimai/public
      - ./var:/opt/kimai/var
`

docker-compose up; docker-compose logs    shows

` 1.8
kimai_1        | Using non mysql DB
kimai_1        | first run - install kimai
kimai_1        |
kimai_1        | Notice: Found invalid "kimai" configuration: Invalid configuration for path "kimai.data_dir": Data directory does not exist in /opt/kimai/src/DependencyInjection/AppExtension.php on line 32
kimai_1        | In BaseNode.php line 441:
kimai_1        |   Invalid configuration for path "kimai.data_dir": Data directory does not exist
kimai_1        | In ExprBuilder.php line 189:
kimai_1        |   Data directory does not exist
kimai_1        | Notice: Found invalid "kimai" configuration: Invalid configuration for path "kimai.data_dir": Data directory does not exist in /opt/kimai/src/DependencyInjection/AppExtension.php on line 32
kimai_1        | In BaseNode.php line 441:
kimai_1        |   Invalid configuration for path "kimai.data_dir": Data directory does not exist
kimai_1        | In ExprBuilder.php line 189:
kimai_1        |   Data directory does not exist
`
directories inside the kimai container are owned by www-data. 

Best regards

M.Honeck

**Comment by kevinpapst** [comment]
Kimai expects the `data` directory to exist in its `var` folder:
execute locally `mkdir -p var/data` inside the folder where `./var:/opt/kimai/var` points to.

EDIT: Actually that is not entirely true, the data directory is configurable:
https://github.com/kevinpapst/kimai2/blob/master/config/packages/kimai.yaml#L301
By default it points to var/data/

**Comment by mh33dev** [comment]
Thanks a lot, manually putting ../data and ../plugins in the var folder helped with the actual error, still wondering why they were not installed in the pull / installation process. Next problem is, that the public folder is empty.

**Comment by kevinpapst** [comment]
They are existing, but if you choose to overwrite them with your own mount, its your responsibility to create them. Same for the public directory.

**Comment by mh33dev** [comment]
Makes sense, - you are responding very quick! Thank you
