### ISSUE TITLE
getting error 500

### ISSUE THREAD

**Issue by nattyluke** [tobybatch/kimai2#119]
docker-compose up stops at Wait for connection...
What am I doing wrong? 
My Mysql db (the container is in another docker-compose file) is working! tried to connect with another container and i could create connection and tables.
So i dont see what im doing wrong. can you help?
`
version: '3.5'
services:
  kimai:
    image: kimai/kimai2:apache-debian-1.9-prod
    networks:
      - docker-server_default
      - mysql_mysql-network
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=kimai.mydomain.de
      - ADMINMAIL=mymail
      - ADMINPASS=mypass
      - DATABASE_URL=mysql://kimai:mysqlpw@mysql:3306/kimai
      - VIRTUAL_HOST=kimai.mydomain.de
      - LETSENCRYPT_HOST=kimai.mydomain.de
      - LETSENCRYPT_EMAIL=mymail
    volumes:
      - ./public:/opt/kimai/public
      - ./var:/opt/kimai/var
    restart: unless-stopped
networks:
  mysql_mysql-network:
    external: true
  docker-server_default:
    external: true

`

**Comment by nattyluke** [comment]
i could swear i testet it: my problem was the port number. after removing it the container starts without a problem:
Kimai2 ready
Still i get error 500 at http://myip:9010/de/homepage

**Comment by kevinpapst** [comment]
@tobybatch @Schrolli91 
why are these volumes existing?
```
- ./public:/opt/kimai/public
- ./var:/opt/kimai/var
```
I kinda understand var/ so the data is persisted outside the container. But the complete public/ ?
Is such a mount not overwriting the Kimai directories and needed files as discussed in #118 ?

**Comment by tobybatch** [comment]
the public one shouldn't be there.  As you point out it'll overwrite the existing files as defined above.  Using the notation:

    public:/opt/kimai/public

Will create a volume containing the files that already exist at the target location.  And it's used to share the public files between the nginx and the fpm containers.

**Comment by tobybatch** [comment]
It's a won't fix as it's not an error with the containers, it's a config error.  I suggest trying a simpler set up to begin with and adding complexity slowly.

**Comment by kevinpapst** [comment]
So there is a difference between 
```
public:/opt/kimai/public
```
and 
```
./public:/opt/kimai/public
```
?

**Comment by oli-ver** [comment]
`public:/opt/kimai/public` together with 
```
volumes:
   public
```
will create a volume in your default docker system location. In my case this is `/var/lib/docker/volumes` (I suppose this can change based on your linux distribution):

```
$ ls -ahl /var/lib/docker/volumes
drwxr-xr-x  3 root root 4,0K Mai 10 12:11 kimai2_public
drwxr-xr-x  3 root root 4,0K Mai 10 12:11 kimai2_var
```
`./public:/opt/kimai/public` on the other hand will map a directory on the level of your docker-compose project. If you for example checked out the git project to `/srv/docker/kimai2` it will create the volume mapping for `/srv/docker/kimai2/public`

**Comment by tobybatch** [comment]
@kevinpapst What Oli-ver say is completely correct with the additional trick that the docker daemon has up it's sleeve.  If you create a system volume in a location on the container that has files in it already, then those files appear in the new container.  e.g.

Create a container with /etc mounted in a system volume:

```bash
tobias@tobias:~ $ docker run -ti -v delme:/etc ubuntu
root@f639eb9b740e:/# ls /etc/
adduser.conf            fstab...
```

Open a new terminal and mount that new system volume in another location:

```bash
tobias@tobias:~ $ docker run -ti -v delme:/otheretc ubuntu
root@f2a5048812b1:/# ls /otheretc/
 adduser.conf            fstab...
```

The first container creates a named system volume (not path) that automatically gets the contents of etc copied into it.  The second mounts that system volume in a different path but the files from the first container are in it. Neat, right.
