### ISSUE TITLE
[QUESTION] InnoDB requirement 

### ISSUE THREAD

**Issue by MRIIOT** [tobybatch/kimai2#122]
I have moved to MariaDB. Is InnoDB engine a requirement?

--default-storage-engine innodb

**Comment by kevinpapst** [comment]
MyISAM ist definitely not supported and I have no experience with other engines.

**Comment by MRIIOT** [comment]
Left MariaDB with InnoDB and 10.3.  10.3.7 InnoDb departed from MySQL 5.7.
