### ISSUE TITLE
Version 1.9 be on docker?

### ISSUE THREAD

**Issue by caprehab** [tobybatch/kimai2#126]
When will version 1.9 be on docker?

_Originally posted by @caprehab in https://github.com/tobybatch/kimai2/issues/123#issuecomment-639760653_

**Comment by caprehab** [comment]
It seems that 1.9 is not working right yet. That is way im asking this.

Changing the yml file to kimai/kimai2:fpm-alpine-1.9-prod will install version 1.9 but im only receiving errors when reacting invoice:

app.CRITICAL: An exception has been thrown during the rendering of a template ("Could not find the entry "invoice" in "/opt/kimai/public/build/entrypoints.json". Found: entrypoints, integrity."). [] []

Also other errors in the log file:
php.CRITICAL: Uncaught Error: Argument 1 passed to Twig\Environment::getTemplateClass() must be of the type string, null given, called in /opt/kimai/vendor/twig/twig/src/Environment.php on line 309 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Twig\\Environment::getTemplateClass() must be of the type string, null given, called in /opt/kimai/vendor/twig/twig/src/Environment.php on line 309 at /opt/kimai/vendor/twig/twig/src/Environment.php:259)"} []

**Comment by kevinpapst** [comment]
Do you have a mount point for the public directory? If so: you need to update its contents.

**Comment by caprehab** [comment]
Thanks, created a new volume. Works now.
