### ISSUE TITLE
[BUG] 500 Internal Server Error"

### ISSUE THREAD

**Issue by lsvivek** [tobybatch/kimai2#130]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container '...'

**Desktop (please complete the following information):**
 - Docker version: [e.g. 19.03.2]
 - Docker compose version: [e.g. 1.21.0]

**Command used to run the container**
 - [e.g. docker run -v ....]

**Docker compose file (with passwords redacted)**

```yaml
version: '3.5'
services:
   image: ...
```

**Additional context**

**Comment by tobybatch** [comment]
@lsvivek I need more info to be able to help you.
