### ISSUE TITLE
[BUG] Problem connection with MySQL database when host port is specified

### ISSUE THREAD

**Issue by LeonardVertighel** [tobybatch/kimai2#134]
**Describe the bug**
Kimai's docker image does not connect to the MySQL database when the DATABASE_URL variable contains the port specification [e.g. 3306].

**To Reproduce**
Steps to reproduce the behaviour:
1. Set the DATABASE_URL variable for mysql: `DATABASE_URL=mysql://kimaiuser:kimaipassword@mysqlhost:mysqlport/kimaidbname`
2. Start the container and show the container logs:  `docker logs KIMAI_CONTAINER_NAME`
3. The container awaits connection to the database indefinitely

**Desktop (please complete the following information):**
 - OS: debian 10
 - Docker version: 19.03.9
 - Docker compose version: not used
 - Ansible: 2.7.7  (used instead of docker compose)

**Additional context**
After some tests I found that, when the port is specified, the `DB_BASE` variable in `startup.sh` is not evaluated correctly.
The `DB_BASE=$(awk -F '[/:@]' '{print $7}' <<< $DATABASE_URL)` command returns the port instead of the database name

I propose the following correction: `DB_BASE=$(awk -F '[/?]' '{print $4}' <<< $DATABASE_URL) `.

**Comment by tobybatch** [comment]
I love a bug that also includes the fix!  Thanks.

I'll test this and include the fix when I get a chance.  Unless you fancy raising a PR and beat me to it.

**Comment by kevinpapst** [comment]
Was that already fixed @tobybatch ?

**Comment by tobybatch** [comment]
No it wasn't.  Thanks Kev.  I'll get on this when I'm back home.
