### ISSUE TITLE
[BUG] sed: bad option in substitution expression when building image

### ISSUE THREAD

**Issue by jokay** [tobybatch/kimai2#136]
**Describe the bug**

Since the change of https://github.com/tobybatch/kimai2/pull/132 the docker image can't be build anymore.

```sh
sed: bad option in substitution expression
The command '

     /bin/sh -c export COMPOSER_HOME=/composer &&
     composer install --working-dir=/opt/kimai --optimize-autoloader &&
     composer clearcache &&
     composer require --working-dir=/opt/kimai laminas/laminas-ldap &&
     chown -R www-data:www-data /opt/kimai &&
     sed "s/128M/256M/g" /usr/local/etc/php/php.ini-development > /usr/local/etc/php/php.ini &&
     sed "s/128M/-1/g" /usr/local/etc/php/php.ini-development > /opt/kimai/php-cli.ini &&
     sed -i "s/env php/env -S php -c /opt/kimai/php-cli.ini/g" /opt/kimai/bin/console

' returned a non-zero code: 1
```

**To Reproduce**

```sh
git clone https://github.com/tobybatch/kimai2.git
cd kimai2
git checkout main
docker build . -t kimai2:latest
```

**Desktop (please complete the following information):**

 - OS: Debian 10
 - Docker version: 19.03.12
 - Docker compose version: 1.26.2

**Command used to run the container**

Not possible to run the container as the build fails.

**Docker compose file (with passwords redacted)**

No docker-compose file used.

**Comment by tobybatch** [comment]
Weird.   It builds fine for me.  Can you check you latest commit hash please?

I'm building against main branch, 

```
tobias@tobias:dockers (main) $ git log                                                      
commit b653f4f6b497c405f946b64c5bcabc0b469e36b7 (HEAD -> main, origin/main)                 
Author: Toby Batch <tobias@neontribe.co.uk>                                                 
Date:   Wed Jul 15 12:30:55 2020 +0100                                                      

    Fix memory limit (#132)
    
    * Fixes memory limit in dev image
    
    * Adds seperate php.ini for console commands
    
    * fixed bad sed line
```

**Comment by jokay** [comment]
I just removed the folder and cloned it again from your repo and the error still occurs.

```sh
user@debian:~/GitHub/kimai2$ git log
commit 5346470e0322b0530126d28c6853b9eda92853ac (HEAD -> main, origin/main, origin/HEAD)
Author: Toby Batch <tobias@neontribe.co.uk>
Date:   Mon Aug 3 10:03:39 2020 +0100

    Delete readme.md
```

**Comment by jokay** [comment]
Builds from this commit works:

```sh
user@debian:~/GitHub/kimai2$ git log
commit 105a3aea94c53e934d57b459c2187b6c73886c41 (HEAD -> main)
Author: D. Domig <x-jokay@users.noreply.github.com>
Date:   Tue Jul 7 21:24:32 2020 +0200

    Update base images (#129)
```

```sh
Successfully built f92abe29990a
Successfully tagged kimai2:latest
```

Do you have the possibility to let it build on [hub.docker.com](https://hub.docker.com) may be on a feature branch?

**Comment by tobybatch** [comment]
Which branch are you on?  

I'll look into hub.docker.com

**Comment by jokay** [comment]
```sh
commit 5346470e0322b0530126d28c6853b9eda92853ac (HEAD -> main, origin/main, origin/HEAD)
```

[latest commit](https://github.com/tobybatch/kimai2/tree/5346470e0322b0530126d28c6853b9eda92853ac) on the `main`.

**Comment by x-jokay** [comment]
[Latest build](https://hub.docker.com/r/kimai/kimai2/builds) on hub.docker.com is from commit [21286088f5fa9cfecb7183e3e66f98ec0aefa13a](https://github.com/tobybatch/kimai2/commit/21286088f5fa9cfecb7183e3e66f98ec0aefa13a).

**Comment by tobybatch** [comment]
You're right, but it only shows when I turn off the docker build kit.  That seems to mask the error.  Thanks, I'll investigate
