### ISSUE TITLE
[FEATURE] Provide a Helm chart for Kimai

### ISSUE THREAD

**Issue by stranljip** [tobybatch/kimai2#148]
**Is your feature request related to a problem? Please describe.**
For the deployment of Kimai on k8s I would like to have a Helm chart which allows an easy deployment and gives the possibility to easily update an existing deployment. Therefore a Helm chart would be really handy.

**Describe the solution you'd like**
I would like to have a Helm chart with a production ready deployment in one of the publicly accessible Helm chart repositories.

**Describe alternatives you've considered**
No real alternative ... one could use the existing docker-compose configuration on a standalone Docker installation but that does not meet my requirements.

**Comment by stranljip** [comment]
I am willing to start work on this, but since I am only starting to create k8s deployment descriptions and Helm charts, this will probably take me a little longer. If anyone has already done work on this, I would be glad to get some pointers in the right direction.

**Comment by stranljip** [comment]
Hi @tobybatch, I actually started working on this. In my fork, I already have the necessary artifacts in order to deploy Kimai with MySQL and Apache via Helm. I think that I will need some more time to enhance and document that, but after that, I would like to reopen the issue and create a PR for that.

**Comment by tobybatch** [comment]
@stranljip That would be great. Does this involve any container changes, or is it just doc changes?

**Comment by stranljip** [comment]
No, I did not change any containers. I use the existing ones and plug them together with Helm. I have not any DevOps experience with Kimai - is it sufficient to have Apache or do nginx/fpm have any substantial advantages over Apache/PHP so that I should support both?

**Comment by tobybatch** [comment]
I wouldn't worry about it from a Helm point of view. The nginx/fpm images tend to be smaller and faster but put up the docs for review and we'll all take a look. 

I suggest a new page relating to Helm deployment and a link in the index page.
