### ISSUE TITLE
Error in installation using composer

### ISSUE THREAD

**Issue by gosymbian** [tobybatch/kimai2#150]
Hi,

I'm trying to install kimai2 on my xampp (windows 7) and I get the following errors :+1: 

C:\xampp\htdocs\kimai\appli>composer install --no-dev --optimize-autoloader
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested PHP extension ext-intl * is missing from your system. Instal
l or enable PHP's intl extension.
  Problem 2
    - The requested PHP extension ext-xsl * is missing from your system. Install
 or enable PHP's xsl extension.
  Problem 3
    - Installation request for lorenzo/pinky 1.0.5 -> satisfiable by lorenzo/pin
ky[1.0.5].
    - lorenzo/pinky 1.0.5 requires ext-xsl * -> the requested PHP extension xsl
is missing from your system.
  Problem 4
    - lorenzo/pinky 1.0.5 requires ext-xsl * -> the requested PHP extension xsl
is missing from your system.
    - twig/inky-extra v3.0.3 requires lorenzo/pinky ^1.0.5 -> satisfiable by lor
enzo/pinky[1.0.5].
    - Installation request for twig/inky-extra v3.0.3 -> satisfiable by twig/ink
y-extra[v3.0.3].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PH
P in CLI mode.

can you advice please, 
thanks in advance,
Domi.

**Comment by kevinpapst** [comment]
You need to install the PHP extensions as the errors indicate.
This is not a Kimai issue, please follow any documentation about that topic in the www.

If you want to use Kimai without docker and have any other question: https://github.com/kevinpapst/kimai2

If you don't know anything about setting up a PHP environment, then you should think about using docker (this repository).

**Comment by gosymbian** [comment]
Hi Kevin,

yes sorry, I have found the solution meanwhile.

btw: thanks for your fast reply and application :-)
Domi.
