### ISSUE TITLE
[BUG] directory "config" is not readable.

### ISSUE THREAD

**Issue by AddoSolutions** [tobybatch/kimai2#166]
**Describe the bug**

During every version of this script I get:

```
[ERROR] File or directory "config" is not readable.      
```

**To Reproduce**
Steps to reproduce the behaviour:

Every version of this app I have tried

**Recommended fix**

In [this file](https://github.com/tobybatch/kimai2/blob/main/startup.sh#L3)

Add to the top:

```
cd /opt/kimai/
```

**Comment by tobybatch** [comment]
Thanks, it's a known bug that is fixed in the  kimai core https://github.com/kevinpapst/kimai2/pull/1951 and will be fixed in the next release of kimai.

**Comment by pbek** [comment]
Thank you for your work on the docker containers, @tobybatch!
Do you know if this already landed in in the current `kimai/kimai2:fpm-alpine-1.10.2-prod` container? I'm getting the same error when I start the kimai docker container.

**Comment by tobybatch** [comment]
It should be fixed in 1.11.1

**Comment by pbek** [comment]
Thank you, do you know a way to see what the current version is in the user interface of Kimai? 😅  I didn't find it anywhere.

**Comment by kevinpapst** [comment]
1. User dropdown upper right corner => About
2. Doctor (pages subtitle)

**Comment by pbek** [comment]
1.10.2. I missed that completely, thank you, @kevinpapst! And thank you for Kimai and a hello from Graz to Vienna! 😁
