### ISSUE TITLE
[BUG] bad parsing for DATABASE_URL with custom port

### ISSUE THREAD

**Issue by fbossiere** [tobybatch/kimai2#169]
**Describe the bug**
Hello,
I am trying to deploy Kimai2 with the following docker : kimai/kimai2:apache-debian-master-prod

I try to point to an external database with custom port (the host looks like : `123.45.67.89:54321`) but the parsing instruction in startup.sh does not get the custom port : `DB_HOST=$(awk -F '[/:@]' '{print $6}' <<< $DATABASE_URL)` . Indeed, the port is separated from the IP due to the use of `:` in the command `-F` of `awk`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Declare any host with a custom port.

Note that various cloud providers host fully managed mysql database with custom ports (like Scaleway) so it is not some kind of exotic need.

**Comment by Schrolli91** [comment]
If you take a look into the startup.sh, you will see its not implemented atm
https://github.com/tobybatch/kimai2/blob/71cde8013cc2a52ea6b2d40eb8c649ac2f41190a/startup.sh#L7

@tobybatch 
Maybe we should collect the DB parameters as separate env vars instead of the whole string.
Would be much easier to handle, i think.

**Comment by fbossiere** [comment]
It is a really small change. Maybe we could deploy a tiny patch ? Because it is totally blocking the deployment of the docker for everyone with custom ports right now :-(

**Comment by tobybatch** [comment]
@Schrolli91 I did originally collect them as different values.  I can't remember why it got changed to one.

I'm on leave with patchy internet, I'll need to make it backward compatible or other deployments could break.

**Comment by wanoo** [comment]
I have personnally recompile this script with this parameter for the PORT

`DB_PORT=$(awk -F '[/:@]' '{print $7}' <<< $DATABASE_URL)`

**Comment by fbossiere** [comment]
This is not good because it will contradict the DB_BASE definition when the port is not defined.

**Comment by wanoo** [comment]
I also have made an if to detect if it's a number or not, and if not use default 3306 ports.

I will try to make a PR il my work give me free time

**Comment by Schrolli91** [comment]
@wanoo that would be nice - thanks ...

**Comment by wanoo** [comment]
PR send

Thx

Regards

**Comment by Schrolli91** [comment]
further discuss - if needed - in the PR
