### ISSUE TITLE
[BUG] Kimai version mismatch

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#185]
@tobybatch I just saw that there are different versions of Kimai mentioned in the Dockerfile.
Is that correct? Is the second variable even needed?

Compare Kimai 1.11.1

https://github.com/tobybatch/kimai2/blob/main/Dockerfile#L16-L18

with Kimai 1.8

https://github.com/tobybatch/kimai2/blob/main/Dockerfile#L178-L180

**Comment by Schrolli91** [comment]
Yes you're right.

The first version number is used to check out the files from github.
The second one is only for the final docker image, to know/tag which kimai version is inside.
Maybe we can change it, so the version number is only mentioned one a single position.

**Comment by kevinpapst** [comment]
Closed by #188 and #189
