### ISSUE TITLE
Create tagged versions 

### ISSUE THREAD

**Issue by schmunk42** [tobybatch/kimai2#19]
Are there plans to create tagged versions, same as the releases at https://github.com/kevinpapst/kimai2/releases

Always running (pulling) a "latest" version can be error prone.

A current workaround for me would be to build an image from `:prod` which does a `git checkout 0.x.y && composer install`. But actually this should be done here I think.

**Comment by tobybatch** [comment]
I've split his out into tagged builds.  Master/latest is build against the source master

https://cloud.docker.com/u/kimai/repository/docker/kimai/kimai2/tags

**Comment by schmunk42** [comment]
Thank you!

btw, the Docker Cloud link above is only available for you (and your team) I think, but for those who are interested, you can see the tags here: https://hub.docker.com/r/kimai/kimai2/tags
