### ISSUE TITLE
[ERROR] Invalid configuration for path "kimai.ldap": LDAP is activated, but the LDAP PHP extension is not loaded.

### ISSUE THREAD

**Issue by zoheirop** [tobybatch/kimai2#191]
Hi guys,

I created a config/packages/local.yaml

After run bin/console cache:clear --env=prod

i get this error 
![ldap error](https://user-images.githubusercontent.com/9295687/98671773-110a1d80-2355-11eb-8eb4-e650249f2b83.PNG)

please any idea about this issue ?
**Additional context**
KIMAI | 1.8
PHP 7.3.4
APP_ENV | prod

regards

**Comment by zoheirop** [comment]
i just install php ldap 
apt install php-ldap

**Comment by Schrolli91** [comment]
@tobybatch shouldn't this included in the image?

**Comment by kevinpapst** [comment]
Kimai 1.8 and "macas01-app10" hostname... is that even a docker image?

**Comment by zoheirop** [comment]
yes @kevinpapst

**Comment by tobybatch** [comment]
This is not our kimai container.  Total red herring.  Hostname wrong, path wrong.

@zoheirop if you believe this is a container then please provide the docker command used to start it, or the docker-compose file.

**Comment by zoheirop** [comment]
hi @tobybatch 
i used this one with docker-compose installation
https://github.com/tobybatch/kimai2

steps :
- cd kimai2
-  git clone https://github.com/tobybatch/kimai2.git
-  ls
-  cd kimai2
-  ls
-  docker compose up
-  sudo docker-compose up

that's take me 5min for the installation :D
and this is the result 
![image](https://user-images.githubusercontent.com/9295687/98737188-28bdc200-23a6-11eb-9727-65343c886e14.png)

regards

**Comment by Schrolli91** [comment]
but on your console screenshot is a local machine, in my opinion.
Thats not the container... How does you join the container to write your commands?

**Comment by kevinpapst** [comment]
In my opinion the problem is fixed and the issue could be locked now.

- The container definitely installs the ldap extension:
https://github.com/tobybatch/kimai2/blob/main/Dockerfile#L95
- Kimai 1.8 is outdated, we cannot support arbitrary old versions.
- If the screenshot is really the docker image, then it is customized (as @tobybatch said: wrong path). And you don't want to open the pandora box of supporting customized images 😁
