### ISSUE TITLE
[FYI] Kimai 1.14 will remove SQLite support

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#223]
The title says it all 😁 

SQLite was always buggy and caused many support requests, so I decided to drop support for it entirely.

This brings at least problems for the [DEV instances](https://tobybatch.github.io/kimai2/dev-instance.html#dev-instances) which are currently using SQLite. 

I think switching to MySQL completely should be no big deal. If you need my input, please let me know!

**Comment by kevinpapst** [comment]
I am removing the documentation for the development images now, as there is no feedback from you guys and because SQLite is not supported any longer - the development docker image will fail soon.

Idea: using an internal mysql for development could replace sqlite.

**Comment by tobybatch** [comment]
Sorry @kevinpapst, I didn't realise you needed anything from us. Yes I agree without sqlite we can't offer a self contained docker image any more. I'll raise a PR to include a `docker-compose.yml` file when the 1.14 image is released.

**Comment by kevinpapst** [comment]
The sqlite docs had to be removed anyways 😄
I thought we might discuss / test a new / or remove the old dev image before 1.14 is released. 
But the other way around is okay as well.

**Comment by kevinpapst** [comment]
BTW. I am removing the Dockerfile from the Kimai repo. It's time to be honest with myself: I can't and won't maintain it.
So yours is the only one available.

**Comment by tobybatch** [comment]
That makes sense, if we replace it with a docker-compose file that points at the `latest` tag then you can keep that is you want. I'll give it some thought.
