### ISSUE TITLE
reverse proxy / jwilder nginx

### ISSUE THREAD

**Issue by FuXXz** [tobybatch/kimai2#231]
Hello everybody,

I'm trying to get Kimai to work. But I got lost. I've tried it for hours now, but I think I don't have the right skills and hope you can help me.

I use the jwilder nginx, this is set up and some other containers are running. But Kimai only gives me 500 or 502 errors. I've tried different images, but I can not make it
kimai / kimai2: apache-debian-1.13-prod
kimai / kimai2: fpm-alpine-1.10.2-prod
kimai / kimai2: latest

The easiest way is to show the composer file, maybe you can help me?

version:'3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - /var/lib/mysql
    networks:
      - kimai
    command: --default-storage-engine innodb
    restart: unless-stopped

  kimai:
    image: kimai/kimai2:latest
    ports:
     - 8001
    networks:
      - kimai
      - service_network #Network from jwilder nginx-proxy
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=localhost,nginx-proxy,${HOSTNAME},127.0.0.1,kimai.mydomaion.de #nginx-proxy = jwilder reverse Proxy Container
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
      - VIRTUAL_PORT=8001
      - VIRTUAL_HOST=kimai.mydomaion.de
      - LETSENCRYPT_HOST=kimai.mydomaion.de
      - LETSENCRYPT_EMAIL=info@mydomain.de

    volumes:
      - public:/opt/kimai/public # << You must use a named volume, see note below
      - var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped

networks:
  kimai:
    name: kimai
    driver: bridge
  service_network:
    external:
      name: service_network #Network from jwilder nginx-proxy
      
volumes:
    var:
    public:

**Comment by tobybatch** [comment]
This is almost certainly a problem with the trusted hosts setting.

Can you attach the logs for start up please?

Check them for line that says unknown trusted host or something like that.

**Comment by FuXXz** [comment]
The Container Kimai Logs has no lines with the word "unknow or trusted"
[_kimai_kimai_1_logs.txt](https://github.com/tobybatch/kimai2/files/6332208/_kimai_kimai_1_logs.txt)

**Comment by tobybatch** [comment]
Well the good news is that your kimai container is running just fine. The problem is with your reverse proxy set up.  Can you try this please? And I'll look at your compose file.  Please change passwords as needed.

```dockerfile
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes: # Uncomment to persist data
       /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    ports:
      - 8001:80
    volumes:
      - public:/opt/kimai/public:ro
    restart: unless-stopped
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  kimai:
    image: kimai2/kimai:fpm-latest-prod
    environment:
      - TRUSTED_HOSTS=localhost
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
      - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1
    volumes:
      - public:/opt/kimai/public
      # - var:/opt/kimai/var
      # - ./ldap.conf:/etc/openldap/ldap.conf:z
      # - ./ROOT-CA.pem:/etc/ssl/certs/ROOT-CA.pem:z
    restart: unless-stopped

  postfix:
    image: catatnight/postfix:latest
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped

  #autoupdate:
  #  image: kimai/kimai2
  #  volumes:
  #      - public:/public
  #      - ./bin/copy-public.sh:/copy-public.sh
  #  entrypoint: /copy-public.sh
  #  user: 0:0

volumes:
    var:
    public:

```

**Comment by FuXXz** [comment]
Hi,
i have deleted all running container / Volumes and set up a clean docker environment.
then i have executed your compose file, which ends with errors

```
Pulling kimai (kimai2/kimai:fpm-latest-prod)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling kimai (kimai2/kimai:fpm-latest-prod)...
ERROR: pull access denied for kimai2/kimai, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

```

**Comment by tobybatch** [comment]
Doh. I'm reworking the tags and docs before kimai 1.14 is released. I'd references the kimai container as a new one only in my local. Change the kimai image to be kimai/kimai2:fpm-alpine-1.10.2-prod

**Comment by FuXXz** [comment]
I also added the server ip to trusted hosts and then it works :(
So that means I can't use kimai with the jwilder nginx?

**Comment by tobybatch** [comment]
I'm sorry, I can't really answer that. I'm sure it's possible but we support the containerization of the kimai app, not every deployment of it.

I can see that the jwilder nginx app is very popular and if someone wants to contribute docs on how to set it up I'm very happy to include them.

One thing I did notice that j don't like is that it mounts the docker socket into the running container. I know why but it is a fairly big security risk as any container can now access the host machine.

Either way, I'm glad it works. I'll close this ticket now, if you have more questions then please open a new one.
