### ISSUE TITLE
Fail on docker swarm

### ISSUE THREAD

**Issue by e-tinchux** [tobybatch/kimai2#233]
Hi Falks! Please, I need some help. I trying to deploy Kimai on my Swarm Cluster using this image "apache-debian-master-prod" but its fails
 
This is the log:
"task: non-zero exit (137): dockerexec: unhealthy container".    

ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |   ++ migrated (took 70221.4ms, used 24M memory)
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |   ++ migrating 20191204120823 (Adds project_start and project_end to projects tables)
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |      -> ALTER TABLE kimai2_projects ADD start DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', ADD end DATETIME DEFAULT NULL COMMENT '(DC2Type:datetime)', ADD timezone VARCHAR(64) DEFAULT NULL
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |   ++ migrated (took 70556.1ms, used 24M memory)
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |   ++ migrating 20200109102138 (Creates comment tables for customers and projects)
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |      -> DELETE from kimai2_configuration WHERE name = "theme.select_type"
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |      -> DELETE from kimai2_roles_permissions WHERE permission = "delete_other_profile"
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |      -> DELETE from kimai2_roles_permissions WHERE permission = "delete_own_profile"
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |      -> CREATE TABLE kimai2_customers_comments (id INT AUTO_INCREMENT NOT NULL, customer_id INT NOT NULL, created_by_id INT NOT NULL, message LONGTEXT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime)', pinned TINYINT(1) DEFAULT '0' NOT NULL, INDEX IDX_A5B142D99395C3F3 (customer_id), INDEX IDX_A5B142D9B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |      -> CREATE TABLE kimai2_projects_comments (id INT AUTO_INCREMENT NOT NULL, project_id INT NOT NULL, created_by_id INT NOT NULL, message LONGTEXT NOT NULL, created_at DATETIME NOT NULL COMMENT '(DC2Type:datetime)', pinned TINYINT(1) DEFAULT '0' NOT NULL, INDEX IDX_29A23638166D1F9C (project_id), INDEX IDX_29A23638B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
ibc-kimai_ibc_kimai.1.nqdqzxdzzpip@dockerworker03    |      -> ALTER TABLE kimai2_customers_comments ADD CONSTRAINT FK_A5B142D99395C3F3 FOREIGN KEY (customer_id) REFERENCES kimai2_customers (id) ON DELETE CASCADE

I'm using this build apache-debian-master-prod with this yml

`version: "3.7"

services:
  ibc_kimai:
    image: kimai/kimai2:apache-debian-master-prod
    depends_on:
      - mariadb #Which we deployed using MariaDB
    volumes:
      - /mnt/ibc/kimai3/public:/opt/kimai/public
      - /mnt/ibc/kimai3/var:/opt/kimai/var
      - /etc/localtime:/etc/localtime:ro
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=0.0.0.0,mariadb
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=xxxxxxxxx
      - "DATABASE_URL=mysql://xxxxxxxx:xxxxxxxxx4@mariadb/kimai_ddbb"
    networks:
      - proxy
      - backend
    deploy:
      placement:
        constraints:
          - node.role == worker
      replicas: 1
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.ibc_kimai.rule=Host(`mydomain`)"
        - "traefik.http.routers.ibc_kimai.tls=true"
        - "traefik.http.routers.ibc_kimai.tls.certresolver=default"
        - "traefik.http.routers.ibc_kimai.entrypoints=websecure"
        - "traefik.http.services.ibc_kimai.loadbalancer.server.port=8001"
        - "traefik.http.services.ibc_kimai.loadbalancer.sticky=true"
        - "traefik.http.services.ibc_kimai.loadbalancer.sticky.cookie.name=StickyCookie"
        - "traefik.http.services.ibc_kimai.loadbalancer.sticky.cookie.secure=true"
volumes:
  public:
    driver: "local"
  var:
    driver: "local"
networks:
  proxy:
    external: true
  backend:
    external: false`

Thanks in advance.
Martín

**Comment by tobybatch** [comment]
It looks like the health check is failing on the container. The health check is this:

```
HEALTHCHECK --interval=20s --timeout=10s --retries=3 \
    CMD curl -f http://127.0.0.1:8001 || exit 1
```

Which executes inside the container. Can you try running it with the health check disabled?

docker-compose.yml, as a setting on the container at the same level as image.
```
    healthcheck:
      disable: true
``` 

If it works then there is an issue with the health check.

**Comment by e-tinchux** [comment]
Thanks @tobybatch !!!

Disable the heathcheck solve my problem!

You can close the ticker
