### ISSUE TITLE
[BUG] ERROR Pulling kimai (kimai2/kimai:latest)

### ISSUE THREAD

**Issue by pete1019** [tobybatch/kimai2#236]
Pulling kimai (kimai2/kimai:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

ERROR: pull access denied for kimai2/kimai, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Could you please help? Thanks

**Comment by pete1019** [comment]
FIX:

You have a typo in every documentation:
its: kimai/kimai2:latest
not: kimai2/kimai:latest

**Comment by tobybatch** [comment]
Thanks, now fixed
