### ISSUE TITLE
[FEATURE] Dynamic listen port passed as environment variable

### ISSUE THREAD

**Issue by jerosa** [tobybatch/kimai2#247]
Allow Kimai to start on a different port instead of always listen to 8001, for example passing it as an environment variable. This will be really helpful in case that port is already used and on cases we want a server with multiple kimai instances (multi tenancy)

**Describe the solution you'd like**
Use an environment variable (KIMAI_PORT) that set the port that will listen Apache/FPM

**Additional context**
We want multiple docker Kimai containers in the same instance and we are not able to do it because we need a custom list of host ports to configure properly the Load Balancers.

**Comment by jerosa** [comment]
This request is due to a limitation of AWS ECS when using the [network mode "awsvpc"](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#network_mode) which requires that the port of the container and the host must be the same. Since docker allows to change the port for the host this feature may not make much sense.

**Comment by tobybatch** [comment]
In both cases the port is not restricted by Kimai, but by the web server that hosts them, either nginx or apache. If you are using nginx then you need to mount your own config, you can change the listen port there.

If you need to change the fpm fast cgi port then I think you'll need to override the file `/usr/local/etc/php-fpm.d/zz-docker.conf`

e.g.
```
volumes:
  - ./zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
```

And change the settings there.

I'd check the details for the underlying container we extend, php:7.4.15-fpm-alpine3.13
