### ISSUE TITLE
[FEATURE] Update docs to link out to external repo

### ISSUE THREAD

**Issue by tobybatch** [tobybatch/kimai2#257]
**Is your feature request related to a problem? Please describe.**
Supporting helm charts

**Describe the solution you'd like**
Link docs out to https://github.com/robjuz/helm-charts/tree/master/charts/kimai2

**Comment by kevinpapst** [comment]
And remove the entire directory https://github.com/tobybatch/kimai2/tree/main/docs/helm ?

**Comment by kevinpapst** [comment]
After having a quick look, I have to say that I am not happy with the link.
The link goes into a deep directory, but from my POV the target repo should be only a Kimai helm chart and nothing more.
Your repo here is MIT, the code of the target repo is based on this repo here(?) but does neither include a license nor the history of contributors.

@robjuz comments?

**Comment by robjuz** [comment]
I will look at it in the evening. I’m at work ;)

W dniu śr., 26.05.2021 o 11:09 Kevin Papst ***@***.***>
napisał(a):

**Comment by robjuz** [comment]
@kevinpapst 
 I'm going to manage multiple charts in a single repo. 

This is why the link point to a deeper directory (to the kimai chart Readme)

My chart is inspired by https://github.com/bitnami/charts/tree/master/bitnami/wordpress

My chart is using bitnami charts as dependencies

Do I need to include a Licence file in my repo? The bitnami charts repo in under Apache License
