### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mircoMar** [tobybatch/kimai2#260]
Hi,
I'm trying to run the latest production build of kimai2 as explained in 

https://tobybatch.github.io/kimai2/

After I run 

docker run --rm --name kimai-mysql-testing -e MYSQL_DATABASE=kimai -e MYSQL_USER=kimai -e MYSQL_PASSWORD=kimai -e MYSQL_ROOT_PASSWORD=kimai -p 3306:3399 -d mysql

I can connect to MySQL (with MySql Workbench for example) on port 3399 either with users root and kimai

when I run 

docker run --rm --name kimai-test -ti -p 8001:8001 -e DATABASE_URL=mysql://kimai:kimai@localhost:3399/kimai kimai/kimai2:apache

or

docker run --rm --name kimai-test -ti -p 8001:8001 -e DATABASE_URL=mysql://root:kimai@localhost:3399/kimai kimai/kimai2:apache

I get the error:

Testing DB:** new \PDO(mysql:host=localhost;dbname=kimai;port=3399, kimai, kimai, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*SQLSTATE[HY000] [2002] No such file or directory (?)Checking DB: 10

Docker version: 20.10.6, build 370c289
OS: Windows 10 Pro 10.0.19042 Build 19042

Thanks,
Mirco

**Comment by tobybatch** [comment]
That port forward looks wrong. You are forwarding the local port 3306 into 3399 in the DB container, which won't connect to anything.

If your SQL Workbench is attaching to a valid DB I think that is your native mysql.

Try swapping the ports around.

**Comment by tobybatch** [comment]
And I don't know how windoze handles name lookups but on a *nix machine localhost is a domain socket, you need to use 127.0.0.1 to access the container.

I don't believe windoze has domain sockets but you could try the IP instead
