### ISSUE TITLE
[BUG] default helm chart not launching

### ISSUE THREAD

**Issue by JustinGuese** [tobybatch/kimai2#261]
**Describe the bug**
I tried to launch kimai with my settings, and as soon as that didn't work I tried launching it with default settings, but it fails.
it seems to install the matching databases, but then when "reloading configurations" it fails. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container 'helm install kiami robjuz/kimai2'
pod/kiami-kimai2-5dccd5f955-rl6b2 in constant crash loop backoff
Crashing after:
```
Kimai2 ready

Reloading configurations ...
============================


 [OK] All 44 YAML files contain valid syntax.                                   



 [OK] All 404 XLIFF files contain valid syntax.                                 


 Rebuilding your cache, please be patient ...

 // Clearing the cache for the prod environment with debug                      
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  


 // Warming up the cache for the prod environment with debug                    
 // false                                                                       

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   


 [OK] Kimai config was reloaded                                                 

[Fri Jun 04 17:08:22.577761 2021] [mpm_prefork:notice] [pid 58] AH00163: Apache/2.4.38 (Debian) PHP/7.4.15 configured -- resuming normal operations
[Fri Jun 04 17:08:22.577918 2021] [core:notice] [pid 58] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

```

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04 
 - Docker version 19.03.15, build 99e3ed8919
 - microk8s --classic --channel=1.21/stable
 - Kubernetes 1.21
 - Helm 3.6.0

**Command used to run the container**
 - helm install kiami robjuz/kimai2

**Additional context**
When I changed MariaDB settings it did not even run the MariaDB container.

**Comment by tobybatch** [comment]
@JustinGuese I don't know much about helm, we recently factored the helm charts off into it's own repo. https://github.com/robjuz/helm-charts/tree/master/charts/kimai2
