### ISSUE TITLE
Separate var directory for install plugin

### ISSUE THREAD

**Issue by rel4xdev** [tobybatch/kimai2#264]
Hi, I am using fpm image with docker composer,
How can I use plugins in this structure without pain :(
I have permission issue for adding and removing plugins

**Comment by tobybatch** [comment]
Just mount a volume into the correct location in the image, assuming you have the `CustomCSSBundle` unpacked into `CustomCSSBundle-1.3` in the same folder as your `docker-compose.yml` then just mount it into your kimai conatainer:

```yaml
...
    volumes:
      - ./CustomCSSBundle-1.3:/opt/kimai/var/plugins/CustomCSSBundle
...
```

You may need to run `bin/console kimai:reload` inside the container for it to be picked up.

**Comment by rel4xdev** [comment]
Thank you toby, problem solved
