### ISSUE TITLE
Set ssl for kimai

### ISSUE THREAD

**Issue by rel4xdev** [tobybatch/kimai2#268]
Hi toby, how can I configure ssl in docker compose file?

**Comment by tobybatch** [comment]
SSL is not a feature of Kimai, but of the web server that serves it. If you are using an nginx (fpm) image then just set that up for SSL. If you are using apache then you will need to mount the certificates into the image using the `-v` or `volumes` settings and then overwrite the apache config to load them something like this:

    docker run -d --name kimai-with-ssl -v /path/to/certs:/certs -v /path/to/apache.conf -p 80:8001 kimai -e DATABASE_URL=mysql://kimai:kimai@${HOSTNAME}:3306/kimai     kimai/kimai2:apache

Exact set ups may vary.
