### ISSUE TITLE
[FEATURE] Update apache-debian-master-prod to latest Kimai Build

### ISSUE THREAD

**Issue by sgaechter** [tobybatch/kimai2#270]
I use the Container "apache-debian-master-prod" for my Kimai2 Installation.
As I saw, the Container is still on v1.13. Is it possible to update this Container to the latest Kimai2 release 1.14.3?

Many thanks for your work deploying all the Containers for Kimai.

**Comment by tobybatch** [comment]
Yes. The containers have been subtly renamed. You want `kimai/kimai2:apache`

Sorry, was in the changelog, I should have shouted louder.
