### ISSUE TITLE
Cannot connect to mysql socket

### ISSUE THREAD

**Issue by igrutje** [tobybatch/kimai2#285]
My setup (synology nas) uses a mariadb with a socket connection, no ports. In the docker environment variable the database url is described like
`mysql://kimai_admin:secret_pw@localhost:3307/kimai?unix_socket=/run/mysqld/mysqld10.sock`
This connection string is derived from [this page](https://www.kimai.org/documentation/synology.html).
Upon starting the docker this gives me the following error message:
`Testing DB:** new \PDO(mysql:host=localhost;dbname=kimai2;port=3307, kimai_admin, secret_pw, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*SQLSTATE[HY000] [2002] No such file or directory (?)Checking DB: 10`

What am I doing wrong.

**Comment by tobybatch** [comment]
Your problem (I think) is the localhost. The container has it's own IP and is a different host to your docker host (the nas).

Switch `localhost` to either the ip or host name of the NAS and try again.

**Comment by igrutje** [comment]
indeed, thanks! Now I have a connection refused error.

**Comment by tobybatch** [comment]
And that is probably the grant on that user being tied down to 127.0.0.1

Not sure what the best solution is, I always use a dedicated m(y|aria) dB in another docker, check the composer examples.

There is no noticeable overhead and it keeps all the data in one place

**Comment by igrutje** [comment]
thanks for the quick response!
