### ISSUE TITLE
Multiple pathes needs to persist during image change [FEATURE]

### ISSUE THREAD

**Issue by Martin-Forster** [tobybatch/kimai2#287]
**Is your feature request related to a problem? Please describe.**
During image update/change some data is lost
example: /var/invoice  ( custom templates for invoices ) 
php.ini 

**Describe the solution you'd like**
I would like a common path to export for data which needs to be persistent across several image versions

**Describe alternatives you've considered**
exporting multiple files and paths, gets messy. i dont like that approach.

**Additional context**
exporting var is not possible because it contains preexisting stuff. We need something like var/custom or instance 
where kimai can store stuff which is data but not in the database.
I guess this has to be realyed to keleo, directly.
To change the folder layout or to store everything in the database, even blobs.

**Comment by kevinpapst** [comment]
Where invoices are stored: https://www.kimai.org/documentation/configurations.html#data-directory
Where invoice templates are searched: https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document

You can change both locations and point to one directory:
- data/invoice-tpl
- data/invoices
- data/...

**Comment by tobybatch** [comment]
@kevinpapst is a super star. You can set these in a local.yaml ad mount that into your image at start time. If you want to add a docs page for this just raise a PR and I'll build it in.

**Comment by Martin-Forster** [comment]
Thanks for the answers, sorry to raise the issue. RTFM would had help.
