### ISSUE TITLE
Ease of Usage/Upgrade[FEATURE]

### ISSUE THREAD

**Issue by evolutionIdGmbH** [tobybatch/kimai2#290]
**Is your feature request related to a problem? Please describe.**
The update process involves manually updating the public volume.

**Describe the solution you'd like**
In my case there are now high performance challenges, it would be enough, to just proxy the static stuff.

For high performance i would suggest to add the public files to the custom nginx container. Through tagging we can make sure that the versions are  consistent.

**Describe alternatives you've considered**
A upgrade shell scripts to manually execute. Which triggers the kimai update command as wells populates a dedicated folder for the transfer to nginx, not the default public.

**Additional context**
Please execuse if i raise dumb questions/issues, im a complete new user to kimai.

**Comment by tobybatch** [comment]
I like the idea but this repo doesn't contain a custom nginx container. I guess we could create one but it would be separate image/container and that container would need to know the version of kimai it was running against.

I'm really bust at my day job ATM, but I'll give it some thought a good idea and keep this issue open.
