### ISSUE TITLE
No Docker Image for 1.15.2 at docker hub

### ISSUE THREAD

**Issue by csageder** [tobybatch/kimai2#298]
**Describe the bug**
There has been a bug fix release 1.15.2 but no new docker image was published to the official docker hub (https://hub.docker.com/r/kimai/kimai2).

**Comment by tobybatch** [comment]
I'm waiting for my co-contributors to review the PR. 

https://github.com/tobybatch/kimai2/pull/297

Hang on...

**Comment by tobybatch** [comment]
I just forced it through.

**Comment by csageder** [comment]
thanks for the fast response
