### ISSUE TITLE
Working with reverse proxy

### ISSUE THREAD

**Issue by noblevirk** [tobybatch/kimai2#3]
I have a nginx-proxy docker-based reverse proxy server w/ SSL enabled that is in front of the docker container running the Kimai2 server.

I can successfully run the docker-compose file of kimai2 itself with no problem, however when I integrate it with [jwilder/nginx-proxy setup ](https://github.com/jwilder/nginx-proxy/blob/master/README.md) things don't work at all. I am greeted with Bad gateway by nginx. 

[docker-compose.yml.log](https://github.com/tobybatch/kimai2/files/2691618/docker-compose.yml.log)

I tried to mount the /opt/kimai as a volume, but that doesn't get mounted either (I suspect this is due to some permission issue) which causes app to crash.

[kimai2.log](https://github.com/tobybatch/kimai2/files/2691617/kimai2.log)

I am using another similar app that is built on Symfony framework called [wallabag](https://github.com/wallabag/docker) that defines bunch of SYMFONY related variables to work behind a reverse proxy. I tried setting these up as well without luck.

Any ideas?
Best regards,
noble

**Comment by noblevirk** [comment]
Update 12/18
The log file as you can see is generating errors, because the docker app couldn't find the database. I have that removed now, I am successfully able to connect to database and verify it using bin/console as follows:

`root@eab63b257b5f:/opt/kimai# ./bin/console doctrine:database:create`

`Could not create database kimai for connection named default
An exception occurred while executing 'CREATE DATABASE kimai':
SQLSTATE[HY000]: General error: 1007 Can't create database 'kimai'; database exists`

I think something in the Symfony framework is causing reverse proxy to break. I tried adding the "TRUSTED_PROXIES" in the docker-compose file to my reverse proxy server's address (which is docker-generated) but due to some permissions issue i get: 

`/startup.sh: line 20: /opt/kimai/,env: Permission denied`
 `/startup.sh: line 23: /opt/kimai/,env: Permission denied`

I logged in the docker-container for the app, by `docker exec -u 0 -it time-app bash` and saw that a new file with `,env` is created and `.env` is not updated. So i updated the `/startup.sh` now the `.env` contains TRUSTED_PROXIES. I also found an error in line 23 of startup.sh, where it wasn't appending the TRUSTED_HOST variable.

Unfortunately, after all that I still can't access it from outside through the reverse proxy :(

**Comment by tobybatch** [comment]
@noblevirk I'm not sure if this will fix your issue but you have found a bug related to the startup.sh

Weirdly I'm using this setup behind a nginx reverse proxy for our complany and didn't hit this problem but anyway I have typo'd the line that sets the trusted proxy, it should read .env not ,env.

Master has been fixed and travis has built it, so can you pull master (or prod image) and try again please.

**Comment by noblevirk** [comment]
@tobybatch 

I figured out what was causing it, I was trying to connect to kimai at port 8000 instead of 8080.

Thank you for your support, please close this issue.
