### ISSUE TITLE
.env File Query

### ISSUE THREAD

**Issue by DustyArmstrong** [tobybatch/kimai2#309]
This isn't a bug but rather for me to understand the functionality. 

I'm adding a plugin ([Easy Backup](https://github.com/mxgross/EasyBackupBundle)) and it uses the .env file to read the parameters to connect to the SQL database. I appreciate I am partially asking about a different repository. My .env file appears to be default:

`DATABASE_URL=mysql://user:password@127.0.0.1:3306/database?charset=utf8&serverVersion=5.7`

Is this expected? When I change it to reflect my compose file, Easy Backup still doesn't connect to the database. In the `docker-compose.yml` file of this repo we pass the environment for the database URL, where is this passed to inside the container if not the .env file? Just so I can understand how I should provide this information to Easy Backup or where I need to make changes. 

Edit: It seems like the Easy Backup plugin is trying to run `/usr/bin/mysqldump` which of course isn't in the container. I assume this will then not work for this setup?

Thank you.

**Comment by tobybatch** [comment]
So there are more than one .env file involved here. The .env file that sits alongside the docker-compose.yml populates environment variables in the docker-compose.

The `environment` section of the docker-compose will set env variables in the running container, **if** they are specified in the `Dockerfile`, e.g. https://github.com/tobybatch/kimai2/blob/main/Dockerfile#L216

What you want is achievable but you will need to build a custom image. Something like this:

`Dockerfile`

```Dockerfile
from kimai/kimai2:apache # <-- or fpm, see below

# install mysqldump in the image
RUN apt install mysql-client

ENV my_var_1=default_value
ENV my_var_2=default_value
ENV my_var_3=default_value
ENV my_var_4=default_value

# Optionally you can copy the extension into place at build time
ADD local-extension-folder /opt/kimai/var/plugins/extension
```

Now you can build it:

    docker build -t my-custom-kimai-image .

And run it with the extra variables set, either on the CLI:

```bash
docker run --rm --name kimai-test \
    -ti \
    -p 8001:8001 \
    -e DATABASE_URL=mysql://kimai:kimai@${HOSTNAME}:3306/kimai \
    -e my_var_1=default_value
    -e my_var_2=default_value
    -e my_var_3=default_value
    -e my_var_4=default_value
    my-custom-kimai-image
```

or in the docker compose file:

```docker-compose
version: '3.5'
services:

    ...
    kimai: # This is the latest FPM image of kimai
      image: kimai/kimai2:fpm
      environment:
        - DATABASE_URL=mysql://kimaiuser:kimaipassword@sqldb/kimai
        -my_var_1=default_value
        -my_var_2=default_value
        -my_var_3=default_value
        -my_var_4=default_value
```

## Apache vs fpm

The apache image is way bigger and is based off the debian base image, use `apt` to add packages. The fpm image is based of the far smaller `alpine` base image and uses `apk` to add packages.

That is all off the top of my head but should work. If you want a custom image built I could do that for you.  It would take about an hour https://github.com/sponsors/tobybatch?frequency=one-time&sponsor=tobybatch

**Comment by DustyArmstrong** [comment]
Thank you for the comprehensive answer. I have a test environment I can try this out with to see what the Easy Backup plugin is doing specifically as well. It's also looking for `git rev-parse HEAD` which I assume is another case of `RUN apk install git` or similar. I would plan to use the `fpm` version. I have the plugins location mounted as a volume for persistence currently and for easier management and updates.

I'm comfortable to do the work and build the custom image myself but happy to donate all the same for your efforts on the project.
