### ISSUE TITLE
This page isn’t working - HTTP ERROR 500

### ISSUE THREAD

**Issue by muzammil22** [tobybatch/kimai2#315]
I deployed the app on shared hosting by creating a folder inside public_html. composer install worked fine. 
I want to know if I still want to serve this app using Synology or it can work in this scenario ?

Steps to reproduce the behaviour:
1. Git clone kimai
2. Composer install

**Desktop (please complete the following information):**
 - standard shared hosting where I host my Wordpress websites

When I go to the directory using my hostname/kimai2/public it shows me "This page isn’t working - HTTP ERROR 500"

Is there anything I am missing here ?

**Comment by muzammil22** [comment]
So I have an update. I installed Symfony in my directory. Now when running " bin/console kimai:install -n" it returns 
"There are no commands defined in the "kimai" namespace.:

Please advise.
Thanks.

**Comment by tobybatch** [comment]
I think you are in the wrong place. This repo just handles the docker image for kimai. You want https://github.com/kevinpapst/kimai2/issues

But I do know that kimai wants to be at the root of a domain, not in a sub folder.

**Comment by muzammil22** [comment]
Apologies. I didn't know that. Will post it in the other thread.
