### ISSUE TITLE
Question: Could not connect to 127.0.0.1:9000

### ISSUE THREAD

**Issue by jbgrobelny** [tobybatch/kimai2#316]
I have Kimai up and running fine, used apache prod. attached to existing MariaDB. Kimai works fine no issues except status of container is unhealthy with error  Could not connect to 127.0.0.1:9000.  Can ping 127.0.0.1 from container but not 127.0.0.1:9000  ( ping: 127.0.0.1:9000: Name or service not known ). any ideas?  
Thanks Joe

**Comment by tobybatch** [comment]
Please fill in a bug ticket. I can't even tell if you are using the apache or fpm image.

https://github.com/tobybatch/kimai2/issues/new?assignees=&labels=&template=bug_report.md&title=%5BBUG%5D+
