### ISSUE TITLE
[BUG] Mismatching build tags

### ISSUE THREAD

**Issue by r0l1** [tobybatch/kimai2#318]
There seams to be a mismatch:
- Latest pushed images are 1.15.3 images (8 days ago), although the latest major and minor version is 1.16 
- The `latest` build tag shows to `fpm-1.15.3-prod`, however it should be 1.16.8
- The 1.16.8 release is missing
Did I miss anything?

**Comment by tobybatch** [comment]
No that's my fault, I built some missing images by hand. Should be fixed now,

**Comment by r0l1** [comment]
Alright! Thank you
