### ISSUE TITLE
+0000 "GET /ping" 404[BUG] 

### ISSUE THREAD

**Issue by ZoXx** [tobybatch/kimai2#319]
Hello all,

I have implemented the Docker version via Portainer.
All variables are implemented, Docker starts, writes to the database but at the end I only get the error mentioned above.

When I call the port on my end, I also get only ERR_EMPTY_RESPONSE.

Is there a bug or is there an incorrect configuration on my part?

Many greetings

My log:

> Wait for MySQL DB connection ...
> Testing DB:** new \PDO(mysql:host=192.168.178.49;dbname=kimai;port=3306, kimai, zQ5yYAH2qtyRyJW82D, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established
> Kimai installation running ...
> Database `kimai` for connection named default already exists. Skipped.
>  [OK] Already at the latest version ("DoctrineMigrations\Version20211008092010")
>  Rebuilding your cache, please be patient ...
>  // Clearing the cache for the prod environment with debug                      
>  // false                                                                       
>  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
>  // Warming up the cache for the prod environment with debug                    
>  // false                                                                       
>  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   
>  [OK] Congratulations! Successfully installed Kimai version 1.16.9              
> Kimai updates running ...
>  [OK] Already at the latest version ("DoctrineMigrations\Version20211008092010")
>  Rebuilding your cache, please be patient ...
>  // Clearing the cache for the prod environment with debug                      
>  // false                                                                       
>  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
>  // Warming up the cache for the prod environment with debug                    
>  // false                                                                       
>  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   
>  [OK] Congratulations! Successfully updated Kimai to version 1.16.9             
> 
> Kimai2 ready
> Reloading configurations ...
>  [OK] All 39 YAML files contain valid syntax.                                   
>  [OK] All 430 XLIFF files contain valid syntax.                                 
>  Rebuilding your cache, please be patient ...
>  // Clearing the cache for the prod environment with debug                      
>  // false                                                                       
>  [OK] Cache for the "prod" environment (debug=false) was successfully cleared.  
>  // Warming up the cache for the prod environment with debug                    
>  // false                                                                       
>  [OK] Cache for the "prod" environment (debug=false) was successfully warmed.   
>  [OK] Kimai config was reloaded                                                 
> [19-Dec-2021 14:39:12] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
> [19-Dec-2021 14:39:12] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
> [19-Dec-2021 14:39:12] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
> [19-Dec-2021 14:39:12] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
> [19-Dec-2021 14:39:12] NOTICE: fpm is running, pid 1
> [19-Dec-2021 14:39:12] NOTICE: ready to handle connections
> 127.0.0.1 -  19/Dec/2021:14:39:19 +0000 "GET /ping" 404
> 127.0.0.1 -  19/Dec/2021:14:39:40 +0000 "GET /ping" 404
> 127.0.0.1 -  19/Dec/2021:14:40:00 +0000 "GET /ping" 404
> 127.0.0.1 -  19/Dec/2021:14:40:20 +0000 "GET /ping" 404

My env:
> ADMINMAIL |  
> ADMINPASS |  
> APP_ENV | prod
> APP_SECRET | NEdjSqUaoSw8Jm36o#s
> DATABASE_URL | mysql://kimai:zQ5yYAH2qtyRyJW82D@192.168.178.49:3306/kimai
> DB_BASE | kimai
> DB_HOST | 192.168.178.49
> DB_PASS | zQ5yYAH2qtyRyJW82D
> DB_PORT | 3306
> DB_TYPE | mysql
> DB_USER | kimai
> GPG_KEYS | 1729F83938DA44E27BA0F4D3DBDB397470D12172 BFDDD28642824F8118EF77909B67A5C12229118F
> KIMAI |  
> MAILER_FROM | kimai@example.com
> MAILER_URL | null://localhost
> PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> PHP_ASC_URL | https://www.php.net/distributions/php-8.0.10.tar.xz.asc
> PHP_CFLAGS | -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
> PHP_CPPFLAGS | -fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
> PHP_EXTRA_CONFIGURE_ARGS | --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data --disable-cgi
> PHP_INI_DIR | /usr/local/etc/php
> PHP_LDFLAGS | -Wl,-O1 -pie
> PHP_SHA256 | 66dc4d1bc86d9c1bc255b51b79d337ed1a7a035cf71230daabbf9a4ca35795eb
> PHP_URL | https://www.php.net/distributions/php-8.0.10.tar.xz
> PHP_VERSION | 8.0.10
> PHPIZE_DEPS | autoconf dpkg-dev dpkg file g++ gcc libc-dev make pkgconf re2c
> TEST_AND_EXIT |  
> TRUSTED_HOSTS | nginx,localhost,127.0.0.1
> TRUSTED_PROXIES | nginx,localhost,127.0.0.1
> TZ | Europe/London

**Comment by tobybatch** [comment]
I haven't used portainer for several years so I'm not sure how to help.

Can you screenshot the portainer setup?

Where is your dB hosted?

Which image are you using?

**Comment by ZoXx** [comment]
Good morning,

> Can you screenshot the portainer setup?

No problem.
[https://www1.xup.in/exec/ximg.php?fid=75240597](https://www1.xup.in/exec/ximg.php?fid=75240597)
[https://www1.xup.in/exec/ximg.php?fid=61007649](https://www1.xup.in/exec/ximg.php?fid=61007649)

> Where is your dB hosted?

Also in Docker. The data is also written to the database.

> Which image are you using?

kimai/kimai2:latest

**Comment by tobybatch** [comment]
I can't see those screen shots. They seem secured.

**Comment by ZoXx** [comment]
Strange. They are public.
We try another hoster.
Here we go:
[https://i.postimg.cc/BnX6ZR7g/SCREEN1.jpg](https://i.postimg.cc/BnX6ZR7g/SCREEN1.jpg)
[https://i.postimg.cc/52TtXpZM/SCREEN2.jpg](https://i.postimg.cc/52TtXpZM/SCREEN2.jpg)

**Comment by tobybatch** [comment]
Sorry, they don't really help. Can you run `docker ps -a` and post the results please?

**Comment by ZoXx** [comment]
Hey,
am no longer at the PC until tomorrow evening. Why does not it help? Everything is visible on both screens from settings to env. What else do you need specifically? The docker listing doesn't help to find the problem or?

Thank you for your Support :)

**Comment by ZoXx** [comment]
- 5182c861beb7   kimai/kimai2:latest             "/bin/sh -c /startup…"   3 days ago    Exited (255) 2 days ago   0.0.0.0:8001->8001/tcp, 9000/tcp                                                         Kimai
- 5e9f65b7a18e   mysql:latest                    "docker-entrypoint.s…"   3 days ago    Up 18 minutes             0.0.0.0:3306->3306/tcp, 33060/tcp                                                        mysql
- 5e43e63b069c   phpmyadmin/phpmyadmin           "/docker-entrypoint.…"   3 days ago    Up 18 minutes             0.0.0.0:7098->80/tcp                                                                    phpmyadmin
- 8871c6ca2a39   portainer/portainer-ce:latest   "/portainer"             5 days ago    Up 18 minutes             0.0.0.0:8000->8000/tcp, 0.0.0.0:9000->9000/tcp, 0.0.0.0:9443->9443/tcp                   Portainer

**Comment by ZoXx** [comment]
Any news? :(

**Comment by tobybatch** [comment]
Hah! it was obvious, I should have seen it earlier. You are running the FPM version without a web server. You need to add an nginx reverse proxy to serve the pages, or swap to the Apache image that bundles the web server.

**Comment by ZoXx** [comment]
> Hah! it was obvious, I should have seen it earlier. You are running the FPM version without a web server. You need to add an nginx reverse proxy to serve the pages, or swap to the Apache image that bundles the web server.

that makes sense! Can you link the docker with apache? Or the docker pull? 
Have a nice christmas and thank you so much!

**Comment by tobybatch** [comment]
I think for you just swap the tab for the kimai from fpm to apache

**Comment by ZoXx** [comment]
Now I can no longer follow.
Can I change the .env variables or do I need to use a different image? If so which one?

**Comment by tobybatch** [comment]
Sorry. Remove the existing kimai image and replace it with apache-prod. Don't change anything else, all the environment variables should not need to change.

**Comment by ZoXx** [comment]
After I changed the image, it now runs clean. Thank you very much!
