### ISSUE TITLE
error after upgrade to 1.4

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [tobybatch/kimai2#33]
Hi,
after upgrading from apache-debian-1.3 to apache-debian-1.4 I receive the following error after logging in:

`
Fatal error: Uncaught Symfony\Component\Debug\Exception\UndefinedFunctionException: Attempted to call function "imagettfbbox" from namespace "Intervention\Image\Gd". in /opt/kimai/vendor/intervention/image/src/Intervention/Image/Gd/Font.php:86 Stack trace: #0 /opt/kimai/vendor/intervention/image/src/Intervention/Image/Gd/Font.php(141): Intervention\Image\Gd\Font->getBoxSize() #1 /opt/kimai/vendor/intervention/image/src/Intervention/Image/Commands/TextCommand.php(30): Intervention\Image\Gd\Font->applyToImage(Object(Intervention\Image\Image), 50, 50) #2 /opt/kimai/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(94): Intervention\Image\Commands\TextCommand->execute(Object(Intervention\Image\Image)) #3 /opt/kimai/vendor/intervention/image/src/Intervention/Image/Image.php(108): Intervention\Image\AbstractDriver->executeCommand(Object(Intervention\Image\Image), 'text', Array) #4 /opt/kimai/vendor/laravolt/avatar/src/Avatar.php(412): Intervention\Image\Image->__call('text', Array) #5 /opt/kimai/vendor/laravol in /opt/kimai/vendor/intervention/image/src/Intervention/Image/Gd/Font.php on line 86`

any idea?

**Comment by kevinpapst** [comment]
Duplicate of #32

**Comment by Schrolli91** [comment]
Should be fixed, so pls try an update

**Comment by tofuSCHNITZEL** [comment]
Yes it's fine now.
