### ISSUE TITLE
Currency Symbol should reflect currency setting 

### ISSUE THREAD

**Issue by ravensorb** [tobybatch/kimai2#341]
**Describe the bug**
Not sure if this is a bug or a feature request.  Right now it seems that all of the currency fields show the Euro Symbol regardless of what currency is set for the customer or project.  If this is a feature request, then it would be great if it was possible to set the default currency for the system and then the symbol should reflect the selected currency.

**To Reproduce**
1. Set currency on customer to USD
2. Save customer
3. Currency symbol still shows Euro

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Docker version: 20.10.12
 - Kimai Version: 1.17.1 prod (Ayumi)

**Comment by tobybatch** [comment]
@kevinpapst Any ideas?

This feels like it's a settings thing. We only containerise the Kimai application but it could be an issue with the server set up in the container. Write permissions or something like that.

Is it the apache or fpm version?

I'd like to see your `docker-compose.yml` or the command you use to start the docker if that's possible?

**Comment by kevinpapst** [comment]
The only reason why this could be a docker issue is invalid ICU data and I highly doubt that.
This is most certainly a misunderstanding how Kimai works or the usual "I did not select a customer, so the currency is unknown for now" problem.
Re-post in the correct repository at https://github.com/kevinpapst/kimai2 - closing here.

**Comment by ravensorb** [comment]
Found it -- looks like it was a combination of a browser cache issue and the symbol defaults to the Euro when loading up.  Shows correct when going back in and editing it.
