### ISSUE TITLE
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by idonos** [tobybatch/kimai2#344]
Hi :) 

We're trying to setup the production image (https://hub.docker.com/r/kimai/kimai2) in our AWS cloud.

When running the container we get

_Wait for MySQL DB connection ...
Testing DB:** new \PDO(mysql:host=kimaitimetracking.[ACCOUNT_ID].eu-central-1.rds.amazonaws.com;dbname=kimai;port=3306, [USERNAME], [PASSWORD], [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Connection established
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
Failed to validate database: An exception occurred in driver:
SQLSTATE[HY000] [2002] No such file or directory
[WARNING] Some commands could not be registered:
In AbstractMySQLDriver.php line 112:
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
In Exception.php line 18:
SQLSTATE[HY000] [2002] No such file or directory
In PDOConnection.php line 40:
...
In PDOConnection.php line 40:
SQLSTATE[HY000] [2002] No such file or directory
Kimai2 ready
[WARNING] Some commands could not be registered:
An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir
...
In PDOConnection.php line 40:
Reloading configurations ...
[OK] All 39 YAML files contain valid syntax.
[OK] All 432 XLIFF files contain valid syntax.
Rebuilding your cache, please be patient ...
// Clearing the cache for the prod environment with debug
// false
[ERROR] An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory
[WARNING] Cache could not be rebuilt.
Please run these commands to rebuild the cache manually:
rm -r var/cache/*
bin/console cache:clear --env=prod
bin/console cache:warmup --env=prod
[Mon Feb 14 17:36:25.668462 2022] [mpm_prefork:notice] [pid 54] AH00163: Apache/2.4.38 (Debian) PHP/8.0.14 configured -- resuming normal operations
[Mon Feb 14 17:36:25.668518 2022] [core:notice] [pid 54] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'_

What causes this error? It seems like Kimai is able to reach the database. So I'm assuming this is not network related.
The image works when I run it locally like described in the doc.

Do I have to add the address of my database instances to the TRUSTED_HOSTS ?

Setup:
- AWS Cloud
- Running container on ECS Fargate
- RDS Database with MySQL 8.23
- Everything is inside a VPC
- Container runs in public subnet
- RDS is placed in private subnet

**Comment by tobybatch** [comment]
TRUSTED_HOSTS is only needed for web requests, so it's not that.

```
SQLSTATE[HY000] [2002] No such file or directory means php cannot find the mysql.default_socket file. Fix it by modifying php.ini file. On Mac it is mysql.default_socket = /tmp/mysql.sock
```

So it is a DB related issue.  

It's being thrown here: https://github.com/tobybatch/kimai2/blob/main/assets/startup.sh#L29

```
  echo "Wait for MySQL DB connection ..."
  until php /dbtest.php $DB_HOST $DB_BASE $DB_PORT $DB_USER $DB_PASS; do
    echo Checking DB: $?
    sleep 3
  done
  echo "Connection established"
}
```

It should loop until dbtest.php exits with a 0 code, so lets look in there. https://github.com/tobybatch/kimai2/blob/main/assets/dbtest.php#L14

```
    $pdo = new \PDO("mysql:host=$DB_HOST;dbname=$DB_BASE;port=$DB_PORT", "$DB_USER", "$DB_PASS", [
        \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION
    ]);
```

That is not throwing an exception. Assuming the things in [] are redacted in your example above then it looks like there is something up with the DB set up. I'm not an AWS expert and have never deployed Kimai to AWS. Can you shell into the running container and run dbtest.php by hand? it should be in /opt/kimai

**Comment by idonos** [comment]
I found this file at the root of my container

_root@ip-10-0-53-7:/# ls
bin  boot  composer  dbtest.php  dev  etc  home  lib  lib64  managed-agents  media  mnt  opt  proc  root  run  sbin  self-test.sh  srv  startup.sh  sys  tmp  use_apache  usr  var
root@ip-10-0-53-7:/# php dbtest.php
PHP Warning:  Undefined array key 1 in /dbtest.php on line 2
PHP Warning:  Undefined array key 2 in /dbtest.php on line 3
PHP Warning:  Undefined array key 3 in /dbtest.php on line 4
PHP Warning:  Undefined array key 4 in /dbtest.php on line 5
PHP Warning:  Undefined array key 5 in /dbtest.php on line 6
Testing DB:** new \PDO(mysql:host=;dbname=;port=, , , [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*SQLSTATE[HY000] [2002] No such file or directory (?)root@ip-10-0-53-7:/# 
root@ip-10-0-53-7:/# 
root@ip-10-0-53-7:/# 
root@ip-10-0-53-7:/# cd opt
root@ip-10-0-53-7:/opt# ls
kimai
root@ip-10-0-53-7:/opt# cd kimai
root@ip-10-0-53-7:/opt/kimai# ls
CHANGELOG.md  CONTRIBUTING.md  LICENSE  README.md  SECURITY.md  UPGRADING.md  assets  bin  composer.json  composer.lock  config  package.json  phpstan.neon  phpunit.xml.dist  public  src  symfony.lock  templates  translations  var  vendor  webpack.config.js  yarn.lock
root@ip-10-0-53-7:/opt/kimai#_ 

/opt/kimai did not contain this file

**Comment by idonos** [comment]
Yes, I redacted the credentials and connection string.
I was able to shell into my container.

The file you were speaking of is located on root.

_root@ip-10-0-5-239:/# ls
bin  boot  composer  dbtest.php  dev  etc  home  lib  lib64  managed-agents  media  mnt  opt  proc  root  run  sbin  self-test.sh  srv  startup.sh  sys  tmp  use_apache  usr  var_

I ran the php script and this is the output:
_root@ip-10-0-5-239:/# php dbtest.php kimaitimetrackingdatabase.[ACCOUNT_ID].eu-central-1.rds.amazonaws.com kimai 3306 [USERNAME] [PASSWORD]
Testing DB:** new \PDO(mysql:host=kimaitimetrackingdatabase.[ACCOUNT_ID].eu-central-1.rds.amazonaws.com;dbname=kimai;port=3306, [USERNAME], [PASSWORD], [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*_

Since no error message was displayed I'm assuming everything worked out.

I ran the same command with a wrong password:

_root@ip-10-0-5-239:/# php dbtest.php kimaitimetrackingdatabase.[ACCOUNT_ID].eu-central-1.rds.amazonaws.com kimai 3306 [USERNAME] thisiswrong
Testing DB:** new \PDO(mysql:host=kimaitimetrackingdatabase.[ACCOUNT_ID].eu-central-1.rds.amazonaws.com;dbname=kimai;port=3306, [USERNAME], thisiswrong, [ \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION ]);*Access denied (1045)_

**Comment by idonos** [comment]
To make sure my connection is really working I've installed mysql cli on my container.

root@ip-10-0-52-117:/# mysql -h kimaitimetrackingdatabase.[ACCOUNT_ID].eu-central-1.rds.amazonaws.com -u [USERNAME] -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 60
Server version: 5.7.34-log Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> use kimai;
Database changed
MySQL [kimai]> show tables;
Empty set (0.001 sec)

MySQL [kimai]>

I'm assuming this is heavily related to PHP & PDO & AWS.

**Comment by idonos** [comment]
I found out what the problem was.
PHP PDO was unable to parse the password which was generated by AWS.

I've generated a new password and now the container does start.

**Comment by tobybatch** [comment]
Thanks for letting me know.
