### ISSUE TITLE
Docker images tagged apache and apache-dev are the same

### ISSUE THREAD

**Issue by keestux** [tobybatch/kimai2#351]
The docker images for `kimai/kimai2` tagged `apache` and `apache-dev` are currently identical. Is this on purpose?

And while we're at it, if I want to run `make` I first have to create a `.env` file. It is not documented what it should contain. I'm guessing that `TIMEZONE` and `KIMAI_VERSION` can be filled in.
```
TIMEZONE=Europe/Amsterdam
KIMAI_VERSION=1.17.1
```
After running `make` I get four tags:
```
localhost/kimai/kimai2                     apache-1.17.1-prod     a21a93a34531  12 minutes ago  707 MB
localhost/kimai/kimai2                     apache-1.17.1-dev      aec114ee34ea  12 minutes ago  700 MB
localhost/kimai/kimai2                     fpm-1.17.1-prod        b3548b99813f  13 minutes ago  403 MB
localhost/kimai/kimai2                     fpm-1.17.1-dev         f0441e061bff  14 minutes ago  396 MB
```

**Comment by tobybatch** [comment]
On the .env you are correct, in fact just the KIMAI_VERSION is all you _need_

As for the images we are migrating to an automated build system. The tagging should happen here:

https://github.com/tobybatch/kimai2/blob/main/.github/workflows/kimai-release.yml#L66

So there are some duplicate image tags, that's to support legacy naming, but the apache and apache-dev should be different. I'll look into it.

**Comment by tobybatch** [comment]
You are completely correct, but I'm not sure why. I'll investigate.

Thank you.
