### ISSUE TITLE
Don't overwrite ports.conf in apache conf

### ISSUE THREAD

**Issue by keestux** [tobybatch/kimai2#354]
At the moment the apache listen port is changed to 8001. This is done by overwriting the default `/etc/apache2/ports.conf`.

I suggest to not do that, because it makes no sense inside the docker environment. Plus it destroys the default listen port 443. (More changes are needed to enable ssl.)

Or, is there another reason to overwrite `ports.conf`?

**Comment by tobybatch** [comment]
There isn't really a good reason to do it, it's just a legacy thing. If I change the internal listen port now I will get _100_s of bugs raised because their installs break. I'll add it as a runtime config option.

**Comment by keestux** [comment]
Maybe we should leave it as is. For me there is no rush anymore, because I've decided to skip the docker installation. It became too complicated to get a decent solution for SSL

**Comment by tobybatch** [comment]
Agreed, most people use the nginx solution for production servers. Then the port/ssl config is handled by a separate container.
