### ISSUE TITLE
Question - nginx-fpm versus apache

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#356]
We were running an earlier version using the nginx proxy and nginx-fpm but are moving to openshift.  Is there an advantage to continuing to use the nginx proxy and nging-fpm instead of apache?  We were thinking of simplifying to just the apache and mysql database containers/pods.

**Comment by tobybatch** [comment]
Nginx is faster and lower memory usage, Apache removes the need for an additional container.  It's kind of up to you. I run an Nginx set up but neither is right or wrong.
