### ISSUE TITLE
Error 500 When I click on "My profile"

### ISSUE THREAD

**Issue by VladimirPuidak** [tobybatch/kimai2#37]
Hey. We used kimai 0.8.1 built on the basis of docker. 10/10/2019 We updated to version kimai / kimai2: apache-debian-1.4.1.

When I click on "My profile" I get an error:
![My profile](https://user-images.githubusercontent.com/21170908/66747837-2da3ff80-ee8e-11e9-882c-0e8210bfb8d0.png)

What logs to show me?

**Comment by Schrolli91** [comment]
Do all other functions still work or will you get this error on each page?

**Comment by VladimirPuidak** [comment]
I get this error only on this page.

**Comment by kevinpapst** [comment]
@organ2 did you test with a SUPER_ADMIN account? Your screenshot shows a very limited user, which is not representative. Login with SUPER_ADMIN, open "Doctor" from the menu and copy&paste the logs here.

**Comment by VladimirPuidak** [comment]
The log file in the attachment
[log.txt](https://github.com/tobybatch/kimai2/files/3724687/log.txt)

**Comment by Schrolli91** [comment]
@kevinpapst do you have any idea if this is an kimai issue or still one from the docker image?

**Comment by kevinpapst** [comment]
Not an Kimai issue.

`The mapping file /opt/kimai/config/serializer/App/API.Model.I18n.yml does not exist`: It looks as if the code (config folder) was only partially updated.
There are files missing and I am not sure what the result is. Maybe the other errors are follow ups (assuming an old cache was used by Symfony).

The other linked #38 issue comes from the same reason, there is an old config loaded with a config key that is no longer supported.

The profile page doesn't load, because the additional Doctrine functions [could not be loaded](https://github.com/kevinpapst/kimai2/blob/master/src/DependencyInjection/Compiler/DoctrineCompilerPass.php): `FUNCTION kimai.strftime does not exist`

The avatar in the upper right clearly says that Kimai >=  1.4 is used and it works, so I guess the fixed docker image is used?! I would concentrate on finding out why the config folder is not up-to-date. Actually I have no clue how the docker images work..., so maybe this is a stupid question: but can we check `git status` of the codebase?

**Comment by Schrolli91** [comment]
@organ2 can you try an docker image with kimai 1.3?
At the moment we have some issues with the kimai 1.4 images, we're working on that.

@kevinpapst yes a `git status` should work inside the container

**Comment by VladimirPuidak** [comment]
> @organ2 can you try an docker image with kimai 1.3?
> At the moment we have some issues with the kimai 1.4 images, we're working on that.

I've updated kimai 0.8.1 to 1.3 on my virtual machine and encountered with same errors. It's erros on my profile page and crashing Kimai when i do export to the pdf file.

**Comment by kevinpapst** [comment]
Did you change any configs on your end @organ2 ?

**Comment by tobybatch** [comment]
@organ2 And can you please share your docker command or docker-compose.yml.

**Comment by VladimirPuidak** [comment]
> Did you change any configs on your end @organ2 ?

I didn't change ane configs. I just changed "image: kimai:0.8.1" to "image: kimai/kimai2:apache-debian-1.4.1" in docker-compose.yml. After that I used this command to update Kimai:
sudo docker-compose up -d --force-recreate

> @organ2 And can you please share your docker command or docker-compose.yml.

My current docker-compose.yml
[removed]

**Comment by Schrolli91** [comment]
@organ2 have removed your compose file - credentials inside !!!

**Comment by tobybatch** [comment]
@organ2 I tested your docker compose with my local set up.  I deleted your volumes, they make no sense for me to use.  My profile does not error.

**Comment by tobybatch** [comment]
can you send me the full hash of your 1.4.1 tag please?

```docker image ls --no-trunc kimai/kimai2:apache-debian-1.4.1```

**Comment by VladimirPuidak** [comment]
> @organ2 have removed your compose file - credentials inside !!!

I changed credentials to wrong. Anyway thank you :)

> can you send me the full hash of your 1.4.1 tag please?
> 
> `docker image ls --no-trunc kimai/kimai2:apache-debian-1.4.1`

[123.txt](https://github.com/tobybatch/kimai2/files/3729867/123.txt)

**Comment by tobybatch** [comment]
Can try and re-pull the 1.4.1 tag please, that may me an out of date tag., kimai/kimai2:apache-debian-1.4.1

    f9fd679ac4c42dff13131904d22c46064e7b3bb502a70a35da2f5374ba34b496

**Comment by VladimirPuidak** [comment]
Do you mean re-pull and rebuild docker image or something else?
Because I tried and found no git commit with such hash in your repo.

**Comment by Schrolli91** [comment]
you have to re-pull the kimai image
https://docs.docker.com/compose/reference/pull/

EDIT:
btw - thats the hash from the dockerhub image

**Comment by VladimirPuidak** [comment]
Hello. Sorry for not writing for so long. I re-pulled the kimai image and now the hash of my 1.4.1 image is f9fd679ac4c42dff13131904d22c46064e7b3bb502a70a35da2f5374ba34b496.
But i got same error on the page "My profile". What else can i try?

**Comment by Schrolli91** [comment]
@organ2 can you try an docker image with kimai 1.3?
At the moment we have some issues with the kimai 1.4 images - maybe thats the reason - we're working on that.

**Comment by VladimirPuidak** [comment]
> @organ2 can you try an docker image with kimai 1.3?
> At the moment we have some issues with the kimai 1.4 images - maybe thats the reason - we're working on that.

I've tried the image 1.3. It didn't help.

Also I installed the docker kimai 1.4.1 on new virtual machine and all works correctly.
Is there a problem in my production database?

**Comment by kevinpapst** [comment]
Did you follow the upgrade guide?

**Comment by VladimirPuidak** [comment]
> Did you follow the upgrade guide?

I just changed the image  0.8.1 to 1.4.1 in the docker-compose.yml and rerun containers.

**Comment by kevinpapst** [comment]
Do you have a local.yaml in place? If so, read the UPGRADING.md .
If not, maybe the database wasn't migrated. Post the contents of the table `migration_versions`.

**Comment by VladimirPuidak** [comment]
> Do you have a local.yaml in place? If so, read the UPGRADING.md .
> If not, maybe the database wasn't migrated. Post the contents of the table `migration_versions`.

Yes, I have a local.yaml. I watched UPGRADING.md, but I understood only that need to give a write access for folder "avatar".
[local_yml.txt](https://github.com/tobybatch/kimai2/files/3768281/local_yml.txt)

What information is needed from the table migration_versions?
![2019-10-24 18_15_41-dbForge Studio 2019 Express for MySQL - Start Page](https://user-images.githubusercontent.com/21170908/67499816-58f6cd80-f68a-11e9-90e1-dc39588d8bae.png)

**Comment by kevinpapst** [comment]
You should check at least the role permissions in local.yaml if you need them (or remove them completely). They were changed and you should adapt your config to make sure that you have the correct permission check (see documentation)

I need the contents of the migration_versions table.
It should contain something like this (obviously only the first column is important):
<img width="345" alt="Bildschirmfoto 2019-10-24 um 17 24 57" src="https://user-images.githubusercontent.com/533162/67500608-39a87200-f683-11e9-9822-947ab74085ea.png">

**Comment by VladimirPuidak** [comment]
Contents of the migration_versions table.
![migration_versions](https://user-images.githubusercontent.com/21170908/67561632-e4716c80-f725-11e9-90d3-1cff73c25c92.png)

**Comment by kevinpapst** [comment]
All migrations ran successful.

Okay, whatever is going on, this is not a Kimai issue. 
The log clearly says that the filesystem contents are not correct (missing configs...).
You could compare the contents against a current clone.

Sorry, but I am out.

**Comment by Schrolli91** [comment]
has you mounted the kimai folder to you host file system?

**Comment by VladimirPuidak** [comment]
Yes, I have the mounted kimai folder. This is a part of my docker-compose.yaml.

kimai:
    image: kimai/kimai2:apache-debian-1.4.1
    environment:
        - APP_ENV=prod
        - DATABASE_URL=mysql://kimaiu:kimaip@mydb/kimai
        ....
        ....
        ....
        ....
    volumes:
        - /var/kimai2/app-repo/config:/opt/kimai/config
    depends_on:
        - mydb
    ports:
        - 8001:8001
    restart: always

**Comment by Schrolli91** [comment]
I think the mounted config is the problem - maybe an old format?
What happens if you remove the config mount? is kimai running correctly then?

**Comment by VladimirPuidak** [comment]
Yes, the problem is in the old file format. I copied the folder "config" from kevinpapst/kimai2, loaded my local.yaml and restarted docker-compose. All my problems have been gone. Thanks for the help.

**Comment by Schrolli91** [comment]
ok, then we can close here?

For further Docker images we try to improve the docs especially for the updating case

**Comment by VladimirPuidak** [comment]
yes
