### ISSUE TITLE
[FEATURE] Test image for the next major release

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#373]
Hi @tobybatch ,

do you think we could work on setting up a docker image for the next major release?
It will probably not be around for a couple of months... but it would be nice to have a test option for all docker users out there. 

As Symfony changed their security system I had to rewrite all authenticators. 
SAML login seems to work, LDAP as well. But both need some extra attention.
For unexplainable reasons 😁 my stomach says that there are still some hidden 🐛 with those new authenticators.
Not only there ... but this is the most important part for the beginning of the tests.

This is the branch: https://github.com/kevinpapst/kimai2/pull/2902
I tried to raise the dependencies to the highest level, so we don't have to update these requirements for the next years => in other words: PHP 8.1.

**Comment by tobybatch** [comment]
I'm working on this, the move to 8.1 means I need to alter the php lib locations.

**Comment by tobybatch** [comment]
#388

**Comment by kevinpapst** [comment]
👍
