### ISSUE TITLE
Kimai crashes when I do export pdf

### ISSUE THREAD

**Issue by VladimirPuidak** [tobybatch/kimai2#38]
After updating kimai 0.8.1 to version kimai / kimai2: apache-debian-1.4.1 I encounered with one more error. 
I open menu "Export", enter some data,  choose "PDF format" and press "export".

![export](https://user-images.githubusercontent.com/21170908/66762734-35c06700-eeaf-11e9-82a1-526c5dd9b1ec.png)

I get the pdf file, but after that Kimai crashed and I get the message below:

![Error](https://user-images.githubusercontent.com/21170908/66763039-c8f99c80-eeaf-11e9-9d31-73bdbf14a2c0.png)

To restore Kimai I need to use the command:
sudo docker-compose up -d --force-recreate

**Comment by kevinpapst** [comment]
Duplicates #37
