### ISSUE TITLE
I'm getting an error on install [BUG] 

### ISSUE THREAD

**Issue by somesmart** [tobybatch/kimai2#384]
**Describe the bug**
When trying to install via the instructions here: https://hub.docker.com/r/kimai/kimai2
I get the following error on Step 2:
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (?)Checking DB: 10

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the instructions at https://hub.docker.com/r/kimai/kimai2
2. Perform step 2
3. See error

**Desktop (please complete the following information):**
 - OS: Debian 11
```
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:39 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:42 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.4
  GitCommit:        212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc:
  Version:          1.1.1
  GitCommit:        v1.1.1-0-g52de29d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by tobybatch** [comment]
I need to see either your docker compose file or the commands you use to start the db and kiimai instances.

**Comment by somesmart** [comment]
I'm not the most experience with docker so I went ahead and did the manual install. But thanks!
