### ISSUE TITLE
[FEATURE] Support for db backups

### ISSUE THREAD

**Issue by 3isenHeiM** [tobybatch/kimai2#386]
**Is your feature request related to a problem? Please describe.**
When installing Kimai with Docker, the image does not come with the tools required to take backups of the DB from the container itself.

Using backup plugins (like https://www.kimai.org/store/maximiliangross-easy-backup-bundle.html) is thus not possible since the kimai docker does not have the `mysql` and `mysqldump` binaries.

**Describe the solution you'd like**
Integrate these utilities in the kimai base docker image so that the application can allow backups afterwards.

**Describe alternatives you've considered**
Installing the binaires after the image building, but then at every pull it'll be reset.
.

**Comment by tobybatch** [comment]
The database is not included in this repo at all. Those tools should exist in the Maria/postfix/mysql container. It's not in the PHP/kimai container's scope to handle SQL commands.

For example we don't mandate mysql. You could connect this image to a postfix db I'd you wanted.

**Comment by kevinpapst** [comment]
Besides the fact that Kimai only supports MySQL: it is a bit strange inversion of responsibility if the application should backup itself. 

You might want to setup a cron command in the DB container to dump the mysql database into a shared directory/volume.

**Comment by 3isenHeiM** [comment]
I definitely will, thanks for the hint.
