### ISSUE TITLE
Docker install got 400: Bad Request error

### ISSUE THREAD

**Issue by fishfish77** [tobybatch/kimai2#391]
Hello,

I set kimai up in 2 docker containers and if I want to connect to the site throught the browser, I only get an error 400...
Can anyone help me please?

Kind regards!
![Screenshot 2022-07-04 144057](https://user-images.githubusercontent.com/108674352/177166598-847fdc2e-526a-4690-b012-56b3099553c8.png)
![Screenshot 2022-07-04 144143](https://user-images.githubusercontent.com/108674352/177166602-3339bbe6-93e1-42de-9c15-c6b524d60afa.png)

**Comment by tobybatch** [comment]
I need more info. which image, which os, how was it started?

**Comment by fishfish77** [comment]
> I need more info. which image, which os, how was it started?

its a debian bullseye in an proxmox ve and following commands:

 sudo docker run  --name kimai-mysql-testing     -e MYSQL_DATABASE=kimai     -e MYSQL_USER=kimai     -e MYSQL_PASSWORD=kimai     -e MYSQL_ROOT_PASSWORD=kimai     -p 3399:3306 -d mysql

 sudo docker run --name kimai-test     -ti     -p 8001:8001     -e DATABASE_URL=mysql://kimai:kimai@192.168.74.13:3399/kimai     kimai/kimai2:apache

**Comment by tobybatch** [comment]
And can I see the log output from the kimai container when the 400 is thrown. I believe this is something to do with your VE

```
400 Bad Request
The HyperText Transfer Protocol (HTTP) 400 Bad Request response status code indicates that the server cannot or will not process the request due to something that is perceived to be a client error (for example, malformed request syntax, invalid request message framing, or deceptive request routing).
```

**Comment by fishfish77** [comment]
[Tue Jul 05 09:55:22.715142 2022] [php:notice] [pid 173] [client 10.0.10.221:54801] [2022-07-05 07:55:22] request.ERROR: Uncaught PHP Exception Symfony\\Component\\HttpKernel\\Exception\\BadRequestHttpException:
"Untrusted Host "192.168.74.13"." at /opt/kimai/vendor/symfony/http-kernel/HttpKernel.php line 83 {"exception":"[object] (Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\BadRequestHttpException(code: 0):
Untrusted Host \\"192.168.74.13\\". at /opt/kimai/vendor/symfony/http-kernel/HttpKernel.php:83, Symfony\\\\Component\\\\HttpFoundation\\\\Exception\\\\SuspiciousOperationException(code: 0):
Untrusted Host \\"192.168.74.13\\". at /opt/kimai/vendor/symfony/http-foundation/Request.php:1197)"} []
localhost:8001 10.0.10.221 - - [05/Jul/2022:09:55:21 +0200] "GET /de/homepage HTTP/1.1" 400 630 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"

**Comment by tobybatch** [comment]
`Untrusted Host "192.168.74.13`

From the troubleshooting docs page:

```
Around nine out of ten of the bugs raised are related to the TRUSTED_HOSTS value. If you get a 500 then check that the TRUSTED_HOSTS environment variable is set to either your hostname or the hostname of your proxy server (nginx etc). In the docker-compose environment that is the container name of the nginx container.
```
