### ISSUE TITLE
500: Internal Server Error on going to settings in prod - Docker

### ISSUE THREAD

**Issue by noblevirk** [tobybatch/kimai2#4]
Hi Toby,

I am wondering if you can take a look at this, i am experiencing this in the docker environment. Kevin says this is a cache issue.

Cross linked: 
https://github.com/kevinpapst/kimai2/issues/480

**Comment by kevinpapst** [comment]
The error message

> SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION kimai.strftime does not exist

tells us, that there is a problem while loading the doctrine/database specific SQL functions. From my experience this error goes away after flushing the cache.

I saw it in my dev environment multiple times when switching the database type during tests without refreshing the cache. But no idea why it might happen without manual config changes.

**Comment by alinefr** [comment]
Same for me. Using mariadb:latest or mysql:latest containers.

**Comment by tobybatch** [comment]
@noblevirk @alinefr Can you let me have some details please?

I guess @noblevirk you are using a docker-compose?  Can I have that so I can replicate.

@alinefr Are you using a docker compose too?

**Comment by alinefr** [comment]
@tobybatch I was using [terraform docker provider](https://www.terraform.io/docs/providers/docker/index.html) reproducing the docker-compose contents. I've just tried plain docker-compose.yml from this repo locally and the same issue appears.

This is the steps I've took:
```
git clone git@github.com:tobybatch/kimai2.git
cd kimai2
docker-compose up -d
docker exec kimai2_kimai_1 bin/console doctrine:schema:create
```
```
! [CAUTION] This operation should not be executed in a production environment!

 Creating database schema...

 [OK] Database schema created successfully!
```
```
docker exec kimai2_kimai_1 bin/console kimai:create-user myuser myemail@myemail.com ROLE_SUPER_ADMIN mypasswd
```
```
[OK] Success! Created user: myuser
```
When i go to `Settings -> Preferences` I get:
```
An exception occurred while executing 'SELECT SUM(k0_.rate) AS sclr_0, SUM(k0_.duration) AS sclr_1, strftime('%m', k0_.start_time) AS sclr_2, strftime('%Y', k0_.start_time) AS sclr_3 FROM kimai2_timesheet k0_ WHERE k0_.start_time > ? AND k0_.end_time IS NOT NULL AND k0_.user = ? GROUP BY sclr_3, sclr_2 ORDER BY sclr_3 DESC, sclr_2 ASC' with params [0, 1]:

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION kimai.strftime does not exist
```
Exactly the same as in my VPS.

**Comment by tobybatch** [comment]
@alinefr It does look look like a cache issue.  For now execute these two commands.

    docker-compose exec kimai bin/console cache:clear
    docker-compose exec kimai bin/console cache:clear --env=dev

I get a fix in soon.

**Comment by kevinpapst** [comment]
Really `dev`?
> docker-compose exec kimai bin/console cache:clear --env=dev

**Comment by tobybatch** [comment]
@alinefr @noblevirk 

I've just pushed a new prod docker that clears the base cache before running.  Please pull and try again.

Thanks.

**Comment by alinefr** [comment]
Hi @tobybatch. Thank you! It's working now for me.

**Comment by alinefr** [comment]
This `until` in prod/startup.sh is bloking kimai2 from starting as database connection is hardcoded. 
```
# If we are mysql wait for it.                
if [[ "${DATABASE_URL}" == mysql* ]]; then
    echo Using Mysql DB
    until mysql -u kimai -pkimai -h db kimai -e "show tables"; do
        >&2 echo "Mysql is unavailable - sleeping"
        sleep 5
    done
else
    echo Using non mysql DB
fi
```
I did make it work without this as [terraform docker provider](https://www.terraform.io/docs/providers/docker/r/container.html) accepts `depends_on`.

**Comment by noblevirk** [comment]
Hi @tobybatch , @alinefr  is correct, i am experiencing similar issue and now the kimai app is stuck waiting for mysql database.

`time-app           | Mysql is unavailable - sleeping`
`time-app           | ERROR 2005 (HY000): Unknown MySQL server host 'db' (-2)`

My database variable is `DATABASE_URL: mysql://kimai:kimai@timedb/kimai` which in this case is  timedb (that is the name of the container I am running the mysql server for kimai). I have set the dependency of timedb using `depends_on` for kimai container, which I named time-app.

I have the timedb running before I launch the time-app, but it appears that time-app doesn't see the mysql because db is not defined.

On a separate note,  It appears I can no longer be the super user in the container either
`docker exec -ti time-app bash` takes me as a www user
`www-data@883b0f60fe98:/$ `

Thus I can't edit or modify the startup.sh to update the db variable for database.

I can bypass and fix the issue by renaming the timedb to db, similar to what toby has in his example docker-compose. But that is less fun  way :)

**Comment by tobybatch** [comment]
@noblevirk @alinefr 

You are both correct, in the composer file I have assumed  the DB name.  For now you can either rename your db host to db (sorry, that's poor) or use a mount command to overwrite the start up script, off the top of my head...

    ........
    services:
        image: kimai/kimai2:prod
        volumes:
            - ./startup.sh:/startup.sh
    ........

You can then add your own start up criteria.  I'll push a patch for the start up script soon.

**Comment by tobybatch** [comment]
@noblevirk @alinefr I have broken out the SQL URL into components to allow better provision for customisation.  See

https://github.com/tobybatch/kimai2/blob/master/docker-compose.yml#L21

and

https://github.com/tobybatch/kimai2/blob/master/prod/README.md
