### ISSUE TITLE
[FEATURE] Open repository feature "discussions" 

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#408]
Hi @tobybatch,

What do you think about opening up the discussions for this repo?
Since I did that in the main Kimai repo, a lot of the same repetitive questions stopped popping up.
People tend to search discussions, but closed issues easily get lost.
Issues are simply not made for storing informations.

Directly in Settings under the "Features" header there is a checkbox for it:
<img width="234" alt="Bildschirmfoto 2022-09-24 um 20 04 58" src="https://user-images.githubusercontent.com/533162/192112377-5b2a9e96-c5e9-4627-837f-e28d60cc90cb.png">

I'd propose to activate that and then we can move topics like #407 there.

**Comment by tobybatch** [comment]
Done. I don't even know it existed.
