### ISSUE TITLE
SELINUX will prevent volume from mountiing properly

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#42]
HI

The volume in the docker compose needs :z at the end in a RHEL installation to correct the permissions.

Tim

**Comment by tobybatch** [comment]
Thanks @timlegge , maybe you could raise a PR for the documentation to fix that for us?

**Comment by timlegge** [comment]
Quite possible.  I am looking right now at the install of kimai2 and need
to use ldap.  So I might have a few things...

**Comment by timlegge** [comment]
One thing I was trying to figure out today is how to get the local.yaml
file created for the ldap configuration...
