### ISSUE TITLE
Bug? Tag: fpm-latest not latest?

### ISSUE THREAD

**Issue by PWolff27** [tobybatch/kimai2#421]
We are using Kimai with Docker on Debian 11 and have written the tag fpm-latest in the docker-compose.yml.
 However, we get version 1.22.1 while the latest version is 1.27.0.

We tried to update Kimai after starting it up but nothing happens. It says that we already got the latest version (1.22.1)

Here are some screenshots out of the docker.compose.yml

![2022-10-21_14h08_02](https://user-images.githubusercontent.com/116357819/197192582-bf09f93f-6c02-47b7-a0bc-9e3be73ff93d.png)
![2022-10-21_14h07_24](https://user-images.githubusercontent.com/116357819/197192584-cd25063f-fb25-4cd1-b1ff-dc4ddda2d67a.png)

Hope anyone can help :)

**Comment by tobybatch** [comment]
Canyou try a manual docker pull please? I see 1.27.0

```
✔  ~/usr/kimai/kimai2 [ main | ✔  ] $ docker pull kimai/kimai2:fpm-latest
fpm-latest: Pulling from kimai/kimai2
Digest: sha256:6f537c5b30f0367609cd80c4636c2c0790178d2ff43b894f41170dd9293c4883
Status: Image is up to date for kimai/kimai2:fpm-latest
docker.io/kimai/kimai2:fpm-latest
✔  ~/usr/kimai/kimai2 [ main | ✔  ] $ docker run --rm -ti --entrypoint sh kimai/kimai2:fpm-latest
/var/www/html $ cd /opt/kimai/
/opt/kimai $ ./bin/console kimai:version
Kimai 1.27.0 by Kevin Papst and contributors.
/opt/kimai $ 
```

**Comment by PWolff27** [comment]
It worked thank you very much. I pulled the latest version manually and after that I started Kimai over docker compose again. Now it is 1.27.0
