### ISSUE TITLE
support for volume mount with uid pid needed

### ISSUE THREAD

**Issue by pinkworld123** [tobybatch/kimai2#422]
Hello,

Please support mount of volume with specific UID and PID so it can match the host UID PID. Currently there are error to mount volume with host path directory. 

Thanks

**Comment by tobybatch** [comment]
What you are actually asking for is run as UID. I can put that on the end of the wish list but it's not a high one. I would instead suggest using docker volumes where the permissions will be handled by the docker daemon.

**Comment by pinkworld123** [comment]
@tobybatch why its low priority, its better to use UID GID for running a docker process, that can be easy also for back up of volume when its easily accessible on normal disk path folder.

For example all docker containers made by this guys supports this by default. may be this can help you as an example.
https://github.com/linuxserver. 

Thank you for reply. and Thanks for your time.

**Comment by tobybatch** [comment]
The docker already deescalates user level to `www-data` before running. Docker volumes are more convenient. 

This repo is supported in my spare time and I have a bunch of features I want to include and, I'm sorry, but this just isn't a very pressing one. Maybe you would like to submit a PR that makes the changes for me? Or sponsor the project.

You could roll your own extended image.

Sorry, I can't just fix it for you.

I have opened #423
