### ISSUE TITLE
[FEATURE] Add sub-customer(service or work requester) per project 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [tobybatch/kimai2#428]
**Is your feature request related to a problem? Please describe.**

Quite often exist following situations : 
1 Project which have 1 customer who basically pay money . 
but inside project also exist multiply sub-customers ( contractors ) who can ask to do different activities. 
And invoicing to main customer have to go per every sub customer. 
I. e . pay main customer but hours calculated per every sub customer. 
Such sub customers can be same in different projects. 
In current moment Kimai does not support sub-customers and i use for such purpose tags. 

**Describe the solution you'd like**
Just need to add field like "Service requester" 

**Describe alternatives you've considered**

In current moment for such purpose i use tags. But usage of tags is not very good for such purpose . I create every sub customer as tag. 

**Additional context**

**Comment by kevinpapst** [comment]
Wrong repository, this is Docker. 
Kimai is here: https://github.com/kevinpapst/kimai2

Not sure if custom-fields might be able to help you. There is a demo existing, where you can test it:
https://www.kimai.org/store/custom-fields-bundle.html

**Comment by jpVm5jYYRE1VIKL** [comment]
This is not what i need. And i not ready to pay 50 Eur for such minor feature.
