### ISSUE TITLE
[TECH DEBT] Build deprecation warnings

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#435]
**Is your feature request related to a problem? Please describe.**

The builds show a warning nowadays about deprecated GitHub action features, e.g.
https://github.com/tobybatch/kimai2/actions/runs/3566944034

<img width="764" alt="Bildschirmfoto 2022-11-28 um 18 19 17" src="https://user-images.githubusercontent.com/533162/204340827-e919760c-fd2b-46f4-a59e-c9136152e687.png">

I fixed that in my builds mainly by bumping the versions in the workflow file.

E.g. from `uses: actions/checkout@v2` to `uses: actions/checkout@v3` in line
https://github.com/tobybatch/kimai2/blob/main/.github/workflows/kimai-release.yml#L18

**Comment by tobybatch** [comment]
Bump

**Comment by tobybatch** [comment]
Closing this as I intend to rewrite the whole CI process
