### ISSUE TITLE
[FEATURE] Use opcache & apcu / Increase performance

### ISSUE THREAD

**Issue by LiaraAlis** [tobybatch/kimai2#438]
Hello together,

I have noticed that my Kimai 2 which runs under Docker is very slow.
After a quick investigation, I found that PHP does not run with either OPcache or APCu.
I suggest including this in the image to greatly increase performance and significantly reduce load times.

**Comment by tobybatch** [comment]
Great idea. I will put it on the Todo list.

**Comment by LiaraAlis** [comment]
Is it possible to include this soon?
My kimai is very slow and I hope that implementing this will speed up the system.

**Comment by tobybatch** [comment]
@LiaraAlis I will get round to this but I'm a volunteer and have a day job so all this needs to be fitted around that. My Kimai time at the moment is preparing for the v2 release.

Please feel free to raise a PR with the changes in it, you'll need to add the extensions around about here:

https://github.com/tobybatch/kimai2/blob/main/Dockerfile#L119

and

https://github.com/tobybatch/kimai2/blob/main/Dockerfile#L227

**Comment by kevinpapst** [comment]
PHP 8.1 has opcache enabled by default in prod. Doesn't it?
What benefit has APCU if the app does not use it?

But if you share the php.ini we can have a look what to improve.
There are about 10 config keys which are really necessary for speed.
Stuff like open_basedir = Off, increase realpath_cache, stop checking timestamps of files, unlimited opcode caching (safe, as a restart happens on updates I guess) ... could make a (huge) difference indeed.

**Comment by tobybatch** [comment]
php.ini from the (fpm) prod image

https://gist.github.com/tobybatch/9c67aca669b7db07a331e659940faa93

**Comment by kevinpapst** [comment]
for testing: https://github.com/tobybatch/kimai2/pull/444
