### ISSUE TITLE
Importing v1 data runs out of memory

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#44]
Hi

I have imported the v1 data from my v1 installation to the mydb docker database.  I am running the following command to import v1 data and it hits a memory limit:

Any ideas?

bin/console doctrine:schema:drop --force && bin/console doctrine:schema:create && bin/console kimai:import-v1 "mysql://user:pwd@containerid:3306/kimai_v1?charset=latin1" "kimai_" "test123" "US" "USD"

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097160 bytes) in /opt/kimai/vendor/symfony/stopwatch/StopwatchEvent.php on line 105
20:34:09 CRITICAL  [php] Fatal Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097160 bytes) ["exception" => Symfony\Component\Debug\Exception\OutOfMemoryException^ { …}]

In StopwatchEvent.php line 105:

  Error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 2097160 bytes)

kimai:import-v1 [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> <connection> <prefix> <password> [<country> [<currency>]]

**Comment by kevinpapst** [comment]
Try to prefix the last bin/console with `php -d memory_limit=-1 bin/console ...`

**Comment by timlegge** [comment]
Will give it a shot right now

**Comment by timlegge** [comment]
That worked.  Thanks very much.
