### ISSUE TITLE
Document Secure LDAP configuration

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#46]
Just some notes on how to configure working secure LDAP (636 SSL or 389 STARTTLS)

1. Create ldap directory
2. In docker-compose.yaml mount local.yaml and ldap directory under kimai volumes:
   - ./local.yaml:/opt/kimai/config/packages/local.yaml:z
   - ./ldap:/etc/ldap:z
3. Copy /etc/ldap/ldap.conf to local ldap directory
4. Create certs directory in local ldap directory
5. Copy Root Certificate for LDAP Server Certificate to local ldap/certs/ directory as ROOT-CA.pem
6. Add the following to the bottom of local ldap/ldap.conf
TLS_CACERT      /etc/ldap/certs/ROOT-CA.pem
7. specify useSsl: true or useStartTls: true in local.yaml file

Start Kimai with docker-compose up

Issues to look for:
1. In local.yaml the host: can be the domain name (example.com)
2. If that results in intermittent failures examine the SSL certificate of the server.  One or more of the servers may be providing a certificate without the domain (example.com) in the Subject Alternative Name (Windows randomly selects the certificate if there are multiple)

**Comment by kevinpapst** [comment]
What about opening up a "tips & tricks" section in the LDAP config page?

Would you be willing to sent in a PR for [this file](https://github.com/kimai/www.kimai.org/blob/master/_documentation/ldap.md)?

**Comment by timlegge** [comment]
I can probably do that.  just wasn't sure about which page

**Comment by tobybatch** [comment]
This belongs in the core docs: https://github.com/kimai/www.kimai.org/blob/master/_documentation/ldap.md
