### ISSUE TITLE
[BUG] /assets/startup.sh line 41 - 44

### ISSUE THREAD

**Issue by sibelle-labs** [tobybatch/kimai2#462]
/startup.sh: line 41: [: : integer expression expected
/startup.sh: line 44: assets/monolog.yaml: No such file or directory

**To Reproduce**
at start 

 - OS: [Red Hat Enterprise Linux release 9.1 (Plow)]
 - Docker version: [Docker version 23.0.0, build e92dd87]
 - Docker compose version: [Docker version 23.0.0, build e92dd87]

**Command used to run the container**
 docker run --rm --name kimai-latest \
    -e DATABASE_URL=mysql://kimai:kimai@${HOSTNAME}:3399/kimai \
    -e TRUSTED_HOSTS=nginx,localhost,127.0.0.1,${HOSTNAME},172.30.128.95 \
    -e USER_ID=33 \
    -e GROUP_ID=33 \
    -v kimai-latest_data:/opt/kimai/var \
    -v /opt/kimai/config/packages/local.yaml:/opt/kimai/config/packages/local.yaml \
    -ti \
    -p 8001:8001 \
    kimai/kimai2:apache

**Docker compose file (with passwords redacted)**
Hmmmm do I have to have a file or do I need a file ?
I'm new to Docker`

can that also be the reason why I can't find any prod.log, etc. under /var/log?
Thanks in advance,

**Comment by sibelle-labs** [comment]
After some small research ...
/startup.sh: line 44 & 51
shouldn't instead "assets/monolog.yaml /opt/kimai/config/packages/monolog.yaml" ->
"cp /assets/monolog.yaml /opt/kimai/config/packages/monolog.yaml" ?

/startup.sh: line 41: [: :  a integer expected but at this point, $KIMAI is empty ...

**Comment by tobybatch** [comment]
Yeah, you are right. I'll push a fix for that. Thanks

**Comment by HWiese1980** [comment]
Has this been fixed on the main branch? I'm still seeing this error in a freshly built docker image.
