### ISSUE TITLE
[BUG] GitHub Page (github.io) 

### ISSUE THREAD

**Issue by dom6770** [tobybatch/kimai2#481]
On the GitHub Page https://tobybatch.github.io/kimai2/ the third command to create a user is wrong.
It should be 

```
    docker exec -ti kimai-test \
        /opt/kimai/bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN
```

not

`    docker exec -ti kimai-test /bin/console kimai:create-user admin admin@example.com ROLE_SUPER_ADMIN`

I assume it's an old command. I was already close to submit a new issue because it was not working when I discovered the command is old and the GitHub repo readme.md is different and does work.

**Comment by tobybatch** [comment]
If you want to be super helpful then raise a PR and I'll merge it, then your github id will be forever present in this repo.
