### ISSUE TITLE
[QUESTION] Mapping twig invoice template

### ISSUE THREAD

**Issue by klangborste** [tobybatch/kimai2#482]
Hello together,

at least for me there is a problem with a custom twig template I used before on docker.
I changed to a newer version now with the image "kimai/kimai2:apache-latest" and I got the problem that my changes on the file that is mapped to the docker container "/opt/kimai/templates/invoice/renderer/default.pdf.twig" are not reflect on the system.

Also if I put an empty file with the name "default.pdf.twig" and map in with volume on the container I can still use the invoice default template.

- Debian 11
- Docker version 23.0.1
- image: kimai/kimai2:apache-latest

**Mapped default.pdf.twig file:**
```yaml
    volumes:
      - $DOCKERDIR/kimai/templates:/opt/kimai/templates/invoice/renderer/
```

<img width="416" alt="image" src="https://user-images.githubusercontent.com/25405503/222288669-fe59ed5c-eb1b-4d8a-bde1-b96cdd7fb3c7.png">

Is there a change where I have to map now my custom twig templates?

Best regards

**Comment by kevinpapst** [comment]
RTM and place the file with a new name in the directory `var/invoices/`
https://www.kimai.org/documentation/invoices.html#create-your-own-invoice-document

Using a software outside of the documented scope might or might not work, but support canÄt be given in such a case 🤷

**Comment by klangborste** [comment]
I did FR already the documentation.....As I also mentioned my custom template did work before, only a new docker image was pulled.
That's why I ask if in context of docker not just Kimai itself something changed? How did I must map a volume from the docker container to custom twig template?
