### ISSUE TITLE
Fehlerhafte Zugangsdaten

### ISSUE THREAD

**Issue by eiswurm** [tobybatch/kimai2#486]
After installing Kimai with Docker and Traefik, I cannot log in with the KIMAI_ADMIN_MAIL and KIMAI_ADMIN_PASS given in the .env File.
<img width="664" alt="Bildschirm­foto 2023-03-18 um 19 53 05" src="https://user-images.githubusercontent.com/20281363/226130200-82b945b8-e758-4306-908a-a147efabc687.png">

Here is my docker-compose.yml
[docker-compose.yml](https://github.com/tobybatch/kimai2/files/11009329/docker-compose.yml.txt)

and my logs:
[docker.log](https://github.com/tobybatch/kimai2/files/11009326/docker.log)

**Comment by tobybatch** [comment]
New images are now built and pushed (including multiarch). I'll close this for now, please open a new ticket if issues persist.
