### ISSUE TITLE
Permission escalations

### ISSUE THREAD

**Issue by tobybatch** [tobybatch/kimai2#49]
@Schrolli91 Building without build kit errors on a permission escalation error here:

https://github.com/tobybatch/kimai2/blob/master/Dockerfile#L221

If you remove the switch to root it can't copy the .env file.  Works fine with build kit.  ANy ideas?

**Comment by Schrolli91** [comment]
The global base build will drop the root permissions - maybe we can remove that an drop it only at the end of the build process

remove:
https://github.com/tobybatch/kimai2/blob/master/Dockerfile#L160
https://github.com/tobybatch/kimai2/blob/master/Dockerfile#L208
https://github.com/tobybatch/kimai2/blob/master/Dockerfile#L221

so the root permissions are only dropped at finish

**Comment by Schrolli91** [comment]
looks like this idea will work?
