### ISSUE TITLE
[BUG] Installation Bug (Problem)

### ISSUE THREAD

**Issue by Kr3yx** [tobybatch/kimai2#493]
Execute this command

docker build -t my-local-kimai .

automatically comes this error message.

![grafik](https://user-images.githubusercontent.com/102902833/227000991-002089ab-98cb-4faa-ab60-d0c32a3d338f.png)

**Comment by tobybatch** [comment]
I have no idea why this is. I think it's to do with your local docker set up not the image. Can you try it without build kit enabled?

```
unset DOCKER_BUILDKIT
```

**Comment by Kr3yx** [comment]
Same issue 

![image](https://user-images.githubusercontent.com/102902833/227181701-195943c1-2e59-4bcc-b5d0-87e487bf857c.png)

**Comment by Kr3yx** [comment]
Isn't it true that I don't have to download anything beforehand? In your manual the first step is the build command

**Comment by tobybatch** [comment]
You need to clone the repo
