### ISSUE TITLE
500: Internal Server Error on on registering new user in prod

### ISSUE THREAD

**Issue by perspicuous** [tobybatch/kimai2#5]
i tried to register a new user with the following settings:

image prod
no settings changed, all default ports exposed.

image prod with mysql database and only 8080 exposed (why is 80 and 8001 exposed by default? only 8080 works for me)

upon clicking register new user or forgot password after running kimai, i get:

(
http://xxxxx:xxxx/de/resetting/request
http://xxxx:xxxx/de/register/
)

Oops! Ein Fehler ist aufgetreten.
500: Internal Server Error
Ein unerwarteter Fehler ist aufgetreten. Möglicherweise haben Sie einen Bug gefunden, daher kontaktieren Sie bitte ihren Administrator wenn der Fehler nach einem erneuten Versuch immer noch vorhanden sein sollte. 

Log says:

192.168.1.106 - - [23/Jan/2019:09:40:47 +0000] "GET /de/register/ HTTP/1.1" 500 810 "http://xxxx:xxxx/de/login" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"

**Comment by perspicuous** [comment]
error on :latest where only port 80 and 8001 is exposed by default and 8001 is taking request:

i guess one difference of :latest and prod is that the error is really shown...


Unable to find template "partials/login_logo.html.twig" (looked into: /opt/kimai/templates, /opt/kimai/vendor/symfony/twig-bridge/Resources/views/Form) in @FOSUser/Resetting/request.html.twig at line 3.

Unable to find template "partials/login_logo.html.twig" (looked into: /opt/kimai/templates, /opt/kimai/vendor/symfony/twig-bridge/Resources/views/Form) in @FOSUser/Registration/register.html.twig at line 3.

**Comment by tobybatch** [comment]
@perspicuous I'll look into this when I get a chance but latest is an alias for the dev image, that's what Kevin, the upstream owner wanted.

The prod image is build to run self configure the DB connection, type, create schema etc.

The Dev image assumes it is running against an internal sqlite image.  Can you try the :prod image please.

**Comment by perspicuous** [comment]
@tobybatch
Okay thank you for the quick response.
prod image results in what is described in the first and initial issue comment.

prod didn't work with internal sqlite, nor Mysql

it looks like it doesnt find the twig file in any case..

**Comment by tobybatch** [comment]
@perspicuous Thanks, I'll take a look soon

**Comment by kevinpapst** [comment]
I guess that `Unable to find template` is a bug in Kimai, I'll check and report back

**Comment by kevinpapst** [comment]
That was a bug, which is now fixed in master. A test was added, so this will not happen again.

**Comment by perspicuous** [comment]
thanks!
