### ISSUE TITLE
[FEATURE] Upgrade to the newest kimai 2.0.22 version (official release)

### ISSUE THREAD

**Issue by bykof** [tobybatch/kimai2#507]
Nothing to explain :D 
Kimai was officially released in 2.0.22

**Comment by kevinpapst** [comment]
The auto-build trigger failed on my side: https://github.com/kimai/kimai/actions/runs/5031770066 🤷 
Will try again with the next release. 

Not sure if @tobybatch has to do anything else for 2.x ?

**Comment by chrisonline** [comment]
Same here. Want to upgrade :-)
Any news about this?

**Comment by kevinpapst** [comment]
I just released 2.0.23 but that trigger did not do anything here:
https://github.com/kimai/kimai/actions/runs/5046689277/jobs/9052560255

Probably @tobybatch deactivated builds to prevent that invalid builds spread into the wild:
https://github.com/tobybatch/kimai2/blob/main/.github/workflows/kimai-release.yml#L4

**Comment by tobybatch** [comment]
I'm on it. New release coming ASAP

**Comment by tobybatch** [comment]
Just triggered a v2 build. I'll keep it manual for now. We'll turn actions back on when I'm happy.

**Comment by tobybatch** [comment]
Tags are built and pushed, they took ages to build...

![Selection_172](https://github.com/tobybatch/kimai2/assets/359791/09c06385-8bad-4a44-a9fa-a00c657af13d)

I left them building overnight. I'll try and check ASAP but I'm at work today. Quick look seems good:

```bash
tobias@tobias:~$ docker run -ti --entrypoint bash kimai/kimai2:fpm-2.0.23-dev
52913cb888d1:/var/www/html# cd /opt/kimai/
52913cb888d1:/opt/kimai# ./bin/console kimai:version
Kimai 2.0.23 by Kevin Papst.
52913cb888d1:/opt/kimai# 
```

**Comment by kevinpapst** [comment]
So we are now waiting for feedback, e.g. from @chrisonline or @bykof ?

**Comment by tobybatch** [comment]
Yes. 

`kimai/kimai2:fpm-dev` is pulling and running the FPM dev image and I get the login screen when using https://github.com/tobybatch/kimai2/blob/main/docker-compose.yml

**Comment by namelivia** [comment]
I tested it briefly and it worked for me, created a new user, logged in and clicked around a bit, started projects, and activities, and tracked some time using `kimai/kimai2:fpm-2.0.23-prod`

**Comment by chrisonline** [comment]
Just updated and it is working so far with "kimai/kimai2:fpm"!
Thanks!

**Comment by vpanchal-code** [comment]
I updated as well and it is working so far with "kimai/kimai2"

The steps I took upgrading from 1.30.11 to 2.0.23:
1. Backed up my database
2. Remove all my plugins
3. Removed mapping for local.yaml on my docker compose.
4. Stopped and removed kimai container (removed the volumes as well)
5. Started the kimai container with the new image
6. Ran the following commands:
```
docker exec --user root kimai chown -R www-data:www-data /opt/kimai/var
docker exec kimai /opt/kimai/bin/console kimai:update
docker exec -ti kimai /opt/kimai/bin/console kimai:reload --env=prod
```

I did receive the following message in the log when I reloaded the cache:
```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 69632 bytes) in /opt/kimai/vendor/twig/twig/src/TokenStream.php on line 41
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /opt/kimai/vendor/symfony/var-dumper/Dumper/CliDumper.php on line 480
```

Regardless the error, I was able to log in and create new time entries. Still testing other functionality.

**Comment by vpanchal-code** [comment]
I was able to resolve the memory size error by adding in the `- memory_limit=256M` as an environment value in my docker compose.
