### ISSUE TITLE
[BUG] Installing InvoiceBundle 2.0 fails

### ISSUE THREAD

**Issue by goforthanddie** [tobybatch/kimai2#508]
Hi there,

thanks for all your effort you have been putting into this. This is really a nice piece of software. Thanks for looking into this. I figured that this might be all the information you need. If not, please let me know and I will provide further information.

Samy

**Describe the bug**
I am running `kimai/kimai2:apache-2.0.23-prod` and tried to install the InvoiceBundle 2.0. However, clearing the cache fails. The file `InvoiceBundle\Tests\Invoice\Renderer\JsonRendererTest.php` fails to load `App\Tests\Invoice\Renderer\RendererTestTrait`. I suspect this is due to the fact that the folder `tests` is removed from kimai by `RUN rm -r tests` in [Dockerfile](https://github.com/tobybatch/kimai2/blob/c2d6e3b5794cc9c680561d41789388fc32c072fc/Dockerfile#LL36C1-L36C1). I removed the folder `Tests` from the plugin's directory and clearing the cache did work then. It seems the plugin runs okay, but I don't know what implications the removal of the folder has. Maybe you could tell me if that is a valid fix or if there is a better option? I assume there might be further plugins with such a folder which might have problems if they are trying to include classes from the missing folder.

**Desktop (please complete the following information):**
 - OS: Debian 10.13
 - Docker version: 24.0.1
 - Docker compose version: 1.21.0

**Comment by kevinpapst** [comment]
Hi Samy,
thanks for the report. I updated the plugin at Lemonsqueezy, you can download the latest version 2.0.2 there, it hopefully fixes your issue.
The tests should not be loaded during container compilation.

**Comment by goforthanddie** [comment]
Hi Kevin,

thanks for the quick reply and fix! Updating has worked without a problem now. I just noticed that the plugin still displays version "2.0.1" instead of "2.0.2" in the system.

Best
Samy

**Comment by kevinpapst** [comment]
Hm, seems I forgot to bump the version number. Happens from time to time. Sorry!

As the cause is solved, I will close here.

Thanks for your feedback 👍
