### ISSUE TITLE
Regarding latest docker image update

### ISSUE THREAD

**Issue by tobybatch** [tobybatch/kimai2#510]
### Discussed in https://github.com/tobybatch/kimai2/discussions/509

<div type='discussions-op-text'>

<sup>Originally posted by **hsachan22** May 24, 2023</sup>
I was using apache tag for running kimai2, but today it didn't worked. I checked dockerhub and found out that image was updated 17 hours ago. So, can anyone help me which tag to use for properly running the image?</div>

**Comment by vpanchal-code** [comment]
I am updated the new fpm images from this morning and it working without any issues:
```
image: kimai/kimai2:fpm-latest
```
Hope this helps. Let me know if you need anything other information

**Comment by tobybatch** [comment]
I've marked this as won't fix as it's issue with extending the container rather than running it.
