### ISSUE TITLE
[BUG] Number and Currency Formatting not working due to missing icu-data-full package

### ISSUE THREAD

**Issue by Birkenstab** [tobybatch/kimai2#511]
Number and Currency Formatting seem not to be working correctly in the fpm docker image. 
![image](https://github.com/tobybatch/kimai2/assets/4836713/27b226f8-a2c1-44d1-a541-e9a10caff4b9)
Deutsch should use comma (,) as decimal delimiter

The apache version seems to be working fine.

# Reproduce
Executing php code with `php -a`:
```php
$formatter = new NumberFormatter('de', NumberFormatter::CURRENCY);
echo $formatter->format(1234567.899, NumberFormatter::TYPE_DEFAULT);
```
Results in: `¤1,234,567.90`
German (de) should use a comma (,) as decimal delimiter.

After installing the `icu-data-full` package via apk the same code results in:
`1.234.567,90 XXX`
Which is correct

# Cause
The package `icu-data-full` seems to be missing, as described in https://stackoverflow.com/questions/73895691/php-numberformatter-always-gives-me-the-default-en-us

**Comment by tobybatch** [comment]
I'll keep this open while we check it's all working now.
