### ISSUE TITLE
[FEATURE] Enhance upgrade guide - upgrade from v1.x to v2.x

### ISSUE THREAD

**Issue by firesurfer** [tobybatch/kimai2#513]
**Is your feature request related to a problem? Please describe.**

I am currently looking into safely upgrading our kimai v.1.17.1 instance to v2.x  If I see it correctly I have to take care of the installed plugins manually: https://www.kimai.org/documentation/updates.html

I guess I have also to take care of the incompatibilities listed here: https://github.com/kimai/kimai/blob/main/UPGRADING.md

**Describe the solution you'd like**

Just an additional section in the upgrade guide https://tobybatch.github.io/kimai2/updating.html which has the information and commands  needed to upgrade from a v1.x instance running in docker to  v2.x

**Comment by tobybatch** [comment]
I'll start on that guide once the other v2 issues are settled.

**Comment by tobybatch** [comment]
Known issue, we are working on new docs ATM
