### ISSUE TITLE
[FEATURE] Provide linux/arm64/v8 build

### ISSUE THREAD

**Issue by mikevdberge** [tobybatch/kimai2#517]
**Is your feature request related to a problem? Please describe.**
The current image does not run on Apple M1 based Mac. 
no matching manifest for linux/arm64/v8 in the manifest list entries

**Describe the solution you'd like**
Provide support for linux/arm64/v8 image for mysql
Change the docker-compose.yml and replace the mysql:5.7 image to mysql/mysql-server

**Comment by tobybatch** [comment]
This isn't really a bug in the image is it?

I'll just need to test the change in SQL server setting on linux and windows.  For now, just change it it in your `docker-compose.yml`

**Comment by tobybatch** [comment]
Should be done now
