### ISSUE TITLE
[BUG] Release 2.0.28 / 2.0.29

### ISSUE THREAD

**Issue by jnfarrelly** [tobybatch/kimai2#527]
For users who have 
Preferences >> Language = English 
With formatting rules then = to DATE - 02AUG23 TIME - HH:mm PRICE - $2,748.93 24-HOUR HR = Yes

Then "Time Tracking" >> "My Times"
Then "Create" (Green Arrow Click Box Top Right of Screen)
Then FROM box format shown as "02Aug2023"    <<<  Should be 02Aug23
Then BUG IS >> "Please Match Reqested Time Format" when save attempted.
Then - will not allow correction to format in FROM window
Then will not allow save of any form

WORKAROUND - Change Preferences >> Language /= English (any other English with non-ddMMMyy format will work.

**Comment by kevinpapst** [comment]
English has different formats than what you describe.
English | Englisch | en | 8/2/23 | 11:11 PM | 12:48 | €2,794.83 | no | no

I also do not understand hat the problem is and how you run 2.0.28 in docker, if the image is not existing yet.
