### ISSUE TITLE
[Documentation] ReadMe on DockerHub contains faulty (legacy?) information on user creation

### ISSUE THREAD

**Issue by manuel-sperrle-stb-de** [tobybatch/kimai2#529]
**Describe the bug**
https://hub.docker.com/r/kimai/kimai2
ReadMe on DockerHub contains faulty (legacy?) information on user creation

This doesnt work:
docker exec -ti kimai-test \
    /opt/kimai/bin/console kimai:create-user admin [admin@example.com](mailto:admin@example.com) ROLE_SUPER_ADMIN

This works:
docker exec -ti kimai-test \
    /opt/kimai/bin/console kimai:user:create admin [admin@example.com](mailto:admin@example.com) ROLE_SUPER_ADMIN

Regards, Manu

**Comment by tobybatch** [comment]
Fixed
