### ISSUE TITLE
[BUG] Error 500 at Plugins after Upgrading 

### ISSUE THREAD

**Issue by dominikjas** [tobybatch/kimai2#533]
**Describe the bug**
Hello,

after I updated the docker-image I added the charset and serverversion at the Database_URL and it seemed like everything is working, but when I click on the plugins button I am getting a Error 500. I did the following:

rm -r cache/*
/opt/kimai/bin/console cache:clear --env=prod
/opt/kimai/bin/console cache:warmup --env=prod
/opt/kimai/bin/console assets:install
cd /var
chown -R :www-data .
chmod -R g+r .
chmod -R g+rw .

**To Reproduce**
Steps to reproduce the behaviour:
Click on Plugins:
![image](https://github.com/tobybatch/kimai2/assets/83553492/4a6c3fe0-0b1c-443e-a955-33a2f3a52079)
![image](https://github.com/tobybatch/kimai2/assets/83553492/b3dfc880-e39c-4309-8ed4-cd002d9fcc69)

This is the log message:
```
[2023-08-21T16:32:06.312824+00:00] request.CRITICAL: Uncaught PHP Exception Symfony\
Component\ErrorHandler\Error\UndefinedMethodError: 
"Attempted to call an undefined method named "setPayload" of class "App\Event\PageActionsEvent". 
Did you mean to call "getPayload"?" at /opt/kimai/var/plugins/KioskBundle/EventSubscriber/PluginActionsSubscriber.php line 65 

{"exception":"[object] (Symfony\\Component\\
ErrorHandler\\Error\\UndefinedMethodError(code: 0): Attempted to call an undefined method named \"setPayload\" of 
class \"App\\Event\\PageActionsEvent\". Did you mean to call \"getPayload\"? at 
opt/kimai/var/plugins/KioskBundle/EventSubscriber/PluginActionsSubscriber.php:65)"} []
localhost:8001 172.16.1.2 - - [21/Aug/2023:17:32:06 +0100] "GET /de_DE/admin/plugins/ HTTP/1.1" 500 1957 
```

**Desktop (please complete the following information):**
 - Windows 11 Pro
 -  Chrome

**Server**:
- Debian 11
 - Docker version: 24.0.4, build 3713ee1
 - Docker compose version: 1.29.2, build 5becea4c

**Docker compose file (with passwords redacted)**

version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    hostname: kunde-zeiterfassung-mysql
    volumes:
      - kimai-mysql:/var/lib/mysql
      - kimai-custom:/opt/kimai/config/packages/
      - kimai-apache2:/etc/apache2/
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=********************
      - MYSQL_ROOT_PASSWORD=****************
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
    networks:
      kunde-zeiterfassung_network:
        ipv4_address: 172.16.1.11

  kimai:
    image: kimai/kimai2:apache-latest
    hostname: kunde-zeiterfassung-kimai
    volumes:
      - kimai-var:/opt/kimai/var
      - kimai-custom:/opt/kimai/config/packages/
      - kimai-apache2:/etc/apache2/
    expose:
      - 8001
    environment:
      - ADMINMAIL=********************
      - ADMINPASS=***************
      - DATABASE_URL=mysql://kimaiuser:******************@172.16.1.11/kimai?charset=utf8&serverVersion=5.7
      - TRUSTED_HOSTS=nginx,localhost,127.0.0.1,zeit.kunde.de
      - TIMEZONE=Europe/Berlin
    restart: unless-stopped
    networks:
      kunde-zeiterfassung_network:
        ipv4_address: 172.16.1.12

volumes:
  kimai-var:
  kimai-mysql:
  kimai-custom:
  kimai-apache2:

networks:
  kunde-zeiterfassung_network:
    external: true

**Comment by kevinpapst** [comment]
Upgrade the plugins to their latest version. You get them at Lemonsqueezy
