### ISSUE TITLE
Next update requires MySQL timezone information

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#54]
Hi!

With the next version, Kimai will require the MySQL timezone information populated.
https://mariadb.com/kb/en/library/mysql_tzinfo_to_sql/

Not sure what that means for your containers. On my systems I had to import them with: 
`mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql`

You can check if they are pre-filled by connecting to the Mysql shell and then `select * from mysql.time_zone;` - if the result is empty you need to issue the above command.

**Comment by Schrolli91** [comment]
thanks for this information... we will check that and put it into the start script if necessary

**Comment by tobybatch** [comment]
@kevinpapst Thank Kev.  I just checked and new mysql containers automatically populate that.

**Comment by kevinpapst** [comment]
Thats good, lets me hope that I will not receive dozend of support requests ^^
