### ISSUE TITLE
[BUG] LDAP not supported in latest docker version

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#55]
**Describe the bug**
LDAP not supported in latest docker version

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container '...'
2. fails to start
3. review logs

kimai_1    | [19-Dec-2019 17:09:29] NOTICE: PHP message: PHP Warning:  PHP Startup: Unable to load dynamic library 'l                  dap.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20180731/ldap.so (Error loading shared library libldap                  -2.4.so.2: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20180731/ldap.so)), /u                  sr/local/lib/php/extensions/no-debug-non-zts-20180731/ldap.so.so (Error loading shared library /usr/local/lib/php/ext                  ensions/no-debug-non-zts-20180731/ldap.so.so: No such file or directory)) in Unknown on line 0
postfix_1  | 2019-12-19 17:09:29,773 INFO spawned: 'postfix' with pid 94
postfix_1  | 2019-12-19 17:09:29,773 INFO success: rsyslog entered RUNNING state, process has stayed up for > than 1                   seconds (startsecs)

**Desktop (please complete the following information):**
Unrelated

**Command used to run the container**
/usr/local/bin/docker-compose up

**Docker compose file (with passwords redacted)**

```version: '3'
services:

  mydb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimai
      - MYSQL_PASSWORD=############
      - MYSQL_ROOT_PASSWORD=############
    volumes:
        - mysql:/var/lib/mysql:z
    networks:
        - kimai2-network
    command: --default-storage-engine innodb
    restart: always

  kimai:
    image: kimai/kimai2:fpm-alpine-1.5-prod
    environment:
        - APP_ENV=dev
        - TRUSTED_HOSTS=localhost
        - DATABASE_URL=mysql://kimai:#######@mydb/kimai
        - ADMINMAIL=##############
        - ADMINPASS=###############
    volumes:
        - ./local.yaml:/opt/kimai/config/packages/local.yaml:z
        - ./ldap:/etc/ldap:z
    networks:
        - kimai2-network
    depends_on:
        - mydb
    ports:
        - 8001:8001
    restart: always

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: example.com
      smtp_user: kimai:kimai
    networks:
      - kimai2-network
    restart: unless-stopped
    restart: always

volumes:
  mysql:

networks:
  kimai2-network:

```

**Additional context**

**Comment by Schrolli91** [comment]
Hello

Thanks for your report. I will take a look at this problem during the weekend.

**Comment by tobybatch** [comment]
@timlegge Have you tried the 1.6 tags?  We re-factored the build process and LDAP may have been missed in the 1.5 tag.  I'll try to rebuild it now.

**Comment by tobybatch** [comment]
Looks like the FPM image is missing a library.  I'm fixing it now.

**Comment by timlegge** [comment]
@tobybatch I noticed the refactoring...  I had not looked back at the repo since I started with an earlier version.  I finally got everything working with the prior version so I figured on a easy upgrade.  It was not :-( .  Thanks for looking and adding the libraries I will test it out and try again.

**Comment by tobybatch** [comment]
@timlegge Sorry still no working in current builds.  I'll fix it over xmas

**Comment by tobybatch** [comment]
Working on it #58
