### ISSUE TITLE
missing swagger.json

### ISSUE THREAD

**Issue by Archi-WeB-tracker** [tobybatch/kimai2#557]
hi, i'm trying to install kimai2 with the container manager on synology DSM 7, and i have this problem after the installation : Bind mount failed: 'volume1/docker/kimai/swagger.json' does not exists. i used the kimai2/ docker.compose.yml  version 3.5.  what goes wrong?  thanks

**Comment by tobybatch** [comment]
You'll need to pull the swagger docs out of the running instance, https://www.kimai.org/documentation/rest-api.html

**Comment by Archi-WeB-tracker** [comment]
Thanks , it‘s running now
