### ISSUE TITLE
[BUG] copy-public.sh: Where is it?

### ISSUE THREAD

**Issue by LiaraAlis** [tobybatch/kimai2#559]
As described in the updating docs, it is possible to add the autoupdate image... https://github.com/tobybatch/kimai2/blob/799a534b8d93d18a2d10573457936a31052ce8e0/docs/updating.md

In the volumes section you can find the following mount:
`- ./bin/copy-public.sh:/copy-public.sh`

But what is this `copy-public.sh`? There is no information about it's content or where to find this file.

**Comment by kevinpapst** [comment]
Scrolling through the GIT history, I can't find when and why it was deleted.
But you can check the history of the docs file and find the related commit, which has this "magic" one-line script:
https://github.com/tobybatch/kimai2/commit/e2b4e7ad8ae782cfddb77cfe1d42222f10fa9998

**Comment by kevinpapst** [comment]
As the entire script is in the "FPM update" example above, I think we can safely remove that part from the docs. 
@tobybatch ?

**Comment by LiaraAlis** [comment]
I also suggest to remove that part. It confused me more than necessary because it works without this. :D

**Comment by kevinpapst** [comment]
Done. 
The new docs are here: https://www.kimai.org/documentation/docker-updates.html
I will update this repo soon to point to the new location

**Comment by kevinpapst** [comment]
BTW: the entire docker is currently being moved over to the main Kimai repo to have only one single point of truth
