### ISSUE TITLE
Stuck at UTC time - Not using docker container time?

### ISSUE THREAD

**Issue by knaku** [tobybatch/kimai2#6]
I am stuck with UTC time when running kimai as a docker instance. I have ensured that both my kimai and mysql docker instance is in the correct timezone and not UTC.

I have tried using both -v /etc/localtime:/etc/localtime:ro and -e "TZ=Continent/City" as well as using tzdata, not that either should give a different result. 

How to repeat:
(Use Amsterdam timezone as an example which is +1 hour of utc time)
docker run --rm -ti -p 8080:8080 --name kimai2 kimai/kimai2 -e "TZ=Europe/Amsterdam" (... etc)

**Comment by tobybatch** [comment]
@knaku I'll support for setting TZ via an env var.  I think this will suffice.

    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

**Comment by kevinpapst** [comment]
Just as quick note: PHP has the `date.timezone` setting, which can interfere with the TZ as well.

And there is an [open PR](https://github.com/kevinpapst/kimai2/pull/372) for Kimai itself regarding timezones.
