### ISSUE TITLE
[BUG] Zend\Ldap is missing

### ISSUE THREAD

**Issue by tobybatch** [tobybatch/kimai2#60]
**Describe the bug**
The ```zend-ldap``` is missing.  I have added it to the Dockerfile but it's not there when I start the container.  I'm at a loss as to why, can you point out my stupid mistake please?

**To Reproduce**
Steps to reproduce the behaviour:
 1. ```git fetch && git checkout bugfix/fpm-ldap-library-ext```
 2. ```docker build -t kimai/kimai2:apache-debian-1.6.2-dev --build-arg BASE=apache-debian --target=dev --no-cache .```
 3. ```cd compose && docker-compose -f docker-compose.base.yml -f docker-compose.apache.dev.yml -f docker-compose.ldap.yml up```
 4. ```docker exec -ti compose_kimai_1 tail -f /opt/kimai/var/log/dev.log```
 5. Open the login page http://localhost:8001/
 6. Try and log in as billiy / password123
 7. The login will fail, check the logs and you will see ```Zend\\Ldap\\Ldap is missing, install it with \"composer require zendframework/zend-ldap\"```

**Additional context**
I am definitely adding the extension.  I must have missed something really obvious.

**Comment by kevinpapst** [comment]
Just a blind guess ... does `php -m|grep ldap` report something in the box?

Afaik you can ONLY install the composer dependency (as seen at
https://github.com/tobybatch/kimai2/blob/bugfix/fpm-ldap-library-ext/Dockerfile#L228)
when the php ldap extension is loaded. 

Probably wrong order of installation? 
First composer then ldap module => failure.
First ldap module, then composer => success?

**Comment by tobybatch** [comment]
@kevinpapst Yes the ldap extension is there.  If I manually install the composer module it works, it's a blonde error in the container set up like being in the wrong folder

**Comment by tobybatch** [comment]
@kevinpapst There is a warning about the Zend LDAP Package.  I'm raising you a PR to switch to laminas/laminas-ldap.  Where is documentation generated from? I can't see it in the repo.

**Comment by kevinpapst** [comment]
@tobybatch https://github.com/kimai/www.kimai.org/blob/master/_documentation/ldap.md

**Comment by Schrolli91** [comment]
Maybe you have to change the order?
```
    composer require --working-dir=/opt/kimai zendframework/zend-ldap && \
    composer install --working-dir=/opt/kimai --no-dev --optimize-autoloader && \
```
so first install the ldap tools and after that do the normal composer install?
Idk if that will help us, but maybe the composer install also need the tools for a correct install?

**Comment by kevinpapst** [comment]
That wouldn't help, as Composer would install everything that is not yet installed before. 

Are you sure that the ldap extension is available and loaded when you install the composer packages? Yes, it looks so from the Dockerfile, as base is built before prod... can you share the build output?

**Comment by tobybatch** [comment]
@kevinpapst the output is very big, checkout this repo and run:

    docker build -t kimai/kimai2:apache-debian-1.6.2-dev --build-arg BASE=apache-debian --target=dev --no-cache .

To start the container without running the app, so you can look around:

    docker run -ti --user=root --entrypoint=/bin/bash kimai/kimai2:apache-debian-1.6.2-dev

And to run it with the app started and ldap configured

    cd compose
    docker-compose -f docker-compose.base.yml -f docker-compose.apache.dev.yml -f docker-compose.ldap.yml up

Tail logs:

    docker exec -ti compose_kimai_1 tail -f /opt/kimai/var/log/dev.log

**Comment by tobybatch** [comment]
It looks like it's working now with the Laminas driver.  I'll set up a valid ldap source and retry

**Comment by tobybatch** [comment]
w00t! fixed for apache-debian, I'll do a set of builds for fpm too

**Comment by kevinpapst** [comment]
That is really weird. It works with the Laminas package, but not the Zend composer package? 
I assume you are using a patched Kimai branch?

**Comment by tobybatch** [comment]
No, there is a bridging package that handles it for us (for now).  I'll raise you a PR soon.
