### ISSUE TITLE
Building nginx ERROR: Cannot locate specified Dockerfile: Dockerfile

### ISSUE THREAD

**Issue by RPHr5TyZ** [tobybatch/kimai2#63]
docker-compose up results in

Building nginx
ERROR: Cannot locate specified Dockerfile: Dockerfile

docker-compose.yml
version: '3.5'
services:

  sqldb:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=kimai
      - MYSQL_USER=kimaiuser
      - MYSQL_PASSWORD=kimaipassword
      - MYSQL_ROOT_PASSWORD=changemeplease
    volumes:
      - /var/lib/mysql
    command: --default-storage-engine innodb
    restart: unless-stopped
    healthcheck:
      test: mysqladmin -pchangemeplease ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3 

  nginx:
    build: compose
    ports:
      - 8001:80
    volumes:
      - ./nginx_site.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - kimai
    volumes:
      - public:/opt/kimai/public
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1 
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3 

  kimai:
    image: kimai/kimai2:fpm-alpine-1.5-prod
    environment:
      - APP_ENV=prod
      - TRUSTED_HOSTS=localhost
      - ADMINMAIL=admin@kimai.local
      - ADMINPASS=changemeplease
    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
    restart: unless-stopped
    healthcheck:
      test: wget --spider http://nginx || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3

  postfix:
    image: catatnight/postfix
    environment:
      maildomain: neontribe.co.uk
      smtp_user: kimai:kimai
    restart: unless-stopped
    restart: always

volumes:
    var:
    public:

**Comment by tobybatch** [comment]
@RPHr5TyZ Which folder was your cli in when you ran this please?

**Comment by RPHr5TyZ** [comment]
@tobybatch I was in my home directory.

**Comment by tobybatch** [comment]
so you will need to relativity pathed to the docker file that builds the nginx container, or you will need to move the Dockerfile and other deps to the correct relative directories.

Try running this from the root of the checked out repo

or copy compose/nginx_site.conf and compose/Dockerfile to your home space and changing the line ```build: compose``` to ```build: .```

**Comment by RPHr5TyZ** [comment]
Kimai is up now! I have to elaborate a bit more. The content of the kimai2 directory was wrongly cloned from the kevinpapst repo. After I cloned from your repo everything went fine. Sorry for the confusion.

Yet credentials superadmin /changeme123 won't let me login...

**Comment by RPHr5TyZ** [comment]
changemeplease did a better job!

**Comment by tobybatch** [comment]
OK, good news.  Was that password miss documented somewhere?
