### ISSUE TITLE
[FEATURE] Add trusted hosts at run time

### ISSUE THREAD

**Issue by tobybatch** [tobybatch/kimai2#70]
**Is your feature request related to a problem? Please describe.**
Trusted hosts need to be set if a reverse proxy is used

**Describe the solution you'd like**
Set the trusted host at run time

**Describe alternatives you've considered**
Mandate the name of the nginx conatiner

**Additional context**
#69 #68

**Comment by kevinpapst** [comment]
Please consider the same for TRUSTED_PROXIES (which is currently missing in the README).

**Comment by tobybatch** [comment]
Closed by #78
