### ISSUE TITLE
[FEATURE] Add docker compose information for secure ldap

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#72]
**Is your feature request related to a problem? Please describe.**
The default config is usable with LDAP as long as you do not enable ssl or tls.  With that enabled via a local.yaml setting useSsl: true or useStartTls: true you will have issues with verifying the ssl key of the server (if it is signed by a non public root)

**Describe the solution you'd like**
Add the following commented out options for the documented docker-compose.yml file

under:

```
kimai:

    volumes:
      - public:/opt/kimai/public
      - var:/opt/kimai/var
```

add:
```
        - ./ldap.conf:/etc/openldap/ldap.conf:z
        - ./MY-ROOT-CA.pem:/etc/ssl/certs/MY-ROOT-CA.pem:z
```

The ldap.conf file should include:

```
#
# LDAP Defaults
#

# See ldap.conf(5) for details
# This file should be world readable but not world writable.

#BASE   dc=example,dc=com
#URI    ldap://ldap.example.com ldap://ldap-master.example.com:666

#SIZELIMIT      12
#TIMELIMIT      15
#DEREF          never
TLS_CACERT      /etc/ssl/certs/MY-ROOT-CA.pem

```

**Describe alternatives you've considered**
no other options if you want ssl/tls for ldap

**Additional context**
none

**Comment by tobybatch** [comment]
@timlegge Feel free to add this in PR.  You are an active participant in the project and we could use the help keep things up to date.  Also this could do with being added to the base Kimai repo too.
