### ISSUE TITLE
[BUG] kimai/kimai2:fpm-alpine-1.7-prod not version 1.7

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#73]
**Describe the bug**
kimai/kimai2:fpm-alpine-1.7-prod does not appear to be version 1.7 of kimai2

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the container '...'
2. check /opt/kimai/src/Constants.php
3. version stil 1.6.2

**Comment by Schrolli91** [comment]
@tobybatch 
 i think the Kimai version build-ARG is missing here
https://github.com/tobybatch/kimai2/blob/1d2210d8b3f95995d1a1a273536d71405964ddc3/bin/build.sh#L32

without the ARG the dockerfile will always build the default - see
https://github.com/tobybatch/kimai2/blob/1d2210d8b3f95995d1a1a273536d71405964ddc3/Dockerfile#L17

**Comment by urinal-cake** [comment]
@Schrolli91 is the solution here to instead modify kimai2/bin/build.sh:32 to include `--build-arg KIMAI=1.7` instead? 

I'm attempting this with a different branch of the kimai2 repository, and am receiving the following error: https://gist.github.com/urinal-cake/f3d6b87da475b6977b4b3fc8fb650b3f

**Comment by Schrolli91** [comment]
should fixed with #75
