### ISSUE TITLE
[BUG] fpm-alpine-master-prod is not latest master

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#81]
**Describe the bug**
fpm-alpine-master-prod is not latest master.  I would expect that fpm-alpine-master-prod would be the latest master version, not the version that was created when the image was last created.

**To Reproduce**
Steps to reproduce the behaviour:
1. docker pull kimai/kimai2:fpm-alpine-master-prod
2. Start the container '...'
3. check the version

**Desktop (please complete the following information):**
n/A

**Command used to run the container**
 sudo docker run --rm --name fpm-alpine-master-prod -d -P CONTAINERID

**Docker compose file (with passwords redacted)**
n/A

**Comment by Schrolli91** [comment]
Problem is, that we want to ship pre-build images.
If we fetch the source on Container start we need a lot more tools inside the container (container size) and that consumes a lot more time to start up the container (composer install ...)

@tobybatch @kevinpapst 
i think its a better idea to remove the "master" image - or we have the possibility to create the master automatically on update of the original kimai source (webhook)

**Comment by tobybatch** [comment]
@Schrolli91 Agreed.  We remove the master tag and include build instructions.

**Comment by kevinpapst** [comment]
Wait, before you delete it ... is there any chance that we build the master image automatically?
Eg. via Travis or Github actions?
I can add a trigger in the main repo or even the build script, no problem.

Maybe we can even automate the complete build and upload process for the tags as well, then no manual works is necessary when I publish a new version!?!

**Comment by Schrolli91** [comment]
i think that should be possible - idk how @tobybatch is building the images atm (by hand/automated)

**Comment by tobybatch** [comment]
<shame face>By hand</shame face> 

After @Schrolli91 updated or build process so the super new faster better way I hadn't travis'd it yet.

I will do, @kevinpapst  we may want a web hook from you on merges/pushes.

**Comment by tobybatch** [comment]
I've removed master from the auto build list.  I'll re-create the travis for this soon and then we can offer an auto build on master
