### ISSUE TITLE
[BUG] TZ not carried through build images

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#82]
**Describe the bug**
TZ not carried through build images

**To Reproduce**
Steps to reproduce the behaviour:
1. run bin/build.sh -t 'Atlantic/Halifax'
2. start the resulting container
3. echo $TZ and verify it is incorrect

**Desktop (please complete the following information):**
n/a

**Command used to run the container**
n/a

**Docker compose file (with passwords redacted)**

n/a

**Additional context**
PR to follow

**Comment by Schrolli91** [comment]
see PR #84
