### ISSUE TITLE
[FEATURE] Add build options for flexibilty

### ISSUE THREAD

**Issue by timlegge** [tobybatch/kimai2#83]
**Is your feature request related to a problem? Please describe.**
The build is fine for creating all images but to create one has no options.  Also, DOCKER_BUILDKIT is incompatible with some docker versions so allow it to be overidden

**Describe the solution you'd like**
Add options to specify the BASE, STAGE and to disable the DOCKER_BUILDKIT

**Describe alternatives you've considered**
hacking the build script for my own purposes

**Additional context**
See forthcoming PR

**Comment by Schrolli91** [comment]
see PR #84
