### ISSUE TITLE
[FEATURE] Change LDAP library from zend to laminas

### ISSUE THREAD

**Issue by kevinpapst** [tobybatch/kimai2#93]
Hi!

As you likely saw in the last weeks, the zend ldap packages are deprecated, because they switched the library name to laminas...

Now a user submitted PRs to fix that [in Kimai](https://github.com/kevinpapst/kimai2/pull/1530) and [the documentation](https://github.com/kimai/www.kimai.org/pull/58).

I want to integrate these changes for 1.9.

But AFAIK the docker scripts have to be changed as well. 
How can be coordinate that? For now it should only affect master and once 1.9 is released the prod images as well...

Please have a look in https://github.com/kevinpapst/kimai2/pull/1530

**Comment by kevinpapst** [comment]
ping @tobybatch @Schrolli91 any feedback possible?
I don't want to break your builds, but don't want to keep the PR open for too long.
Code is not like wine, it tends to get worse over time 😁

**Comment by Schrolli91** [comment]
Unfortunately, I don't know anything about ldap - so i think i'am the false person for this feature.

**Comment by tobybatch** [comment]
Looks good for me.  It should just get built when the build happens.

**Comment by tobybatch** [comment]
@kevinpapst Go ahead and merge the PR.  I'll test the next tagged release

**Comment by kevinpapst** [comment]
I was pretty sure that you have a `composer require zendframework/zend-ldap` somewhere in your build scripts, which would have to be replaced as well... the only reason why I was bugging you ;-) 
Isn't that the case anymore?

**Comment by tobybatch** [comment]
I believe that is an alias to the laminas package, I'll factor it out when the core is updated.

**Comment by kevinpapst** [comment]
Still a full repository:
https://github.com/zendframework/zend-ldap/blob/master/composer.json
So it will break. But okay, then lets wait for the next release.
