### ISSUE TITLE
[FEATURE] disable user registration

### ISSUE THREAD

**Issue by sputnik73** [tobybatch/kimai2#94]
**Is your feature request related to a problem? Please describe.**

User registration is configurable in kimai local.yaml (default enabled), I would like to disable registration: https://www.kimai.org/documentation/users.html#user-registration

**Describe the solution you'd like**

To set this option in local.yaml, an environment variable would be helpful and the easiest way to change this setting.

**Describe alternatives you've considered**
Otherwise I would have to mount a custom local.yaml or restrict access to the registration url in the proxy webserver.

Best regards,
Oliver

**Comment by tobybatch** [comment]
I see your issue but there are so many different options that could be set we can't cherry pick a few without being inundated with requests for all of them.

Settings like these should be set in a custom.yml and mounted into .

**Comment by sputnik73** [comment]
Thanks! Your suggestion that for custom settings like this a mounted custom.yml is best practice is helpful, I was not aware of that.

**Update**: i couldn't find any code/documentation about support of a custom.yml file yet.

**Comment by kevinpapst** [comment]
Call it local.yaml, otherwise you might not be able to overwrite all settings!

**Comment by sputnik73** [comment]
Thx. I didn't dare to replace the default local.yaml because there is a good chance something will break when the provided local.yaml is modified some day. I still feel better in simply restricting requests to /registration in nginx than in completely overruling a foreign generated local.yaml.

I am new to this and I agree you can't add environment variables for tons of options. Any way to modify options without completely overruling the existing local.yml would be great. Maybe support for an optional custom.yml ;-)

**Comment by pbek** [comment]
For others who were seeking the same:

I added a volume for `./kimai/local.yaml` to he `kimai` section of my `docker-compose.yml`:

```yml
    volumes:
      - ./kimai/local.yaml:/opt/kimai/config/packages/local.yaml
```

Content of `./kimai/local.yaml`:

```yml
kimai:
  user:
    registration: false
```

**Comment by sputnik73** [comment]
> I added a volume for `./kimai/local.yaml` to he `kimai` section of my `docker-compose.yml`:

great, thank you.
