### ISSUE TITLE
[BUG] /opt/kimai/installed doesn't exist after container is recreated

### ISSUE THREAD

**Issue by moisei** [tobybatch/kimai2#96]
**Describe the bug**
**startup.sh** is using file **/opt/kimai/installed** as an indication that kimai is running first time.
This way once kimai container is removed and created again, startup.sh executing kimai:install and wipes the data from the database, even if the DB is full of data.

**To Reproduce**
```
docker-compose up -d
work with kimai for a while, create some data
docker-compose down (or docker-compose rm kimai)
docker-compose up -d 

```
Note - all the data has lost.

**Additional context**
I am using the latest version of kamai and the latest version of this repo for deploy. The issue is critical because it prevents smooth updates of the system and unaware admins could destroy production data.

**Comment by kevinpapst** [comment]
It is not the fault of `kimai:install`, as this command will NOT delete existing data.  You can run it as often as you want.

Are the database files inside the container or in a mounted directory?

**Comment by moisei** [comment]
@kevinpapst database is on the mounted volume and as the matter of the fact, the data is lost every time I recreate the container. Note that startup.sh also creates superadmin user if this file doesn't exist, 
```
    if [ ! -z "$ADMINPASS" ] && [ ! -a "$ADMINMAIL" ]; then
      /opt/kimai/bin/console kimai:create-user superadmin $ADMINMAIL ROLE_SUPER_ADMIN $ADMINPASS
    fi
```
so it clearly expects an empty DB in this case. if it is not ```kimai:install``` then it is something else that deletes the data. It is easy to reproduce. Run it once, create new user, remove the container and create it again.

**Comment by moisei** [comment]
I've just reviewed my docker compose and I've found my mistake there. Once fixed, the issues is not reproduced. The cause of the mistake was multiple ```volumes:``` entry under the service. It seems docker-compose silently ignores all of them but the last one.

**Comment by kevinpapst** [comment]
Thanks for your feedback!
