### ISSUE TITLE
[BUG] startup.sh fails if MYSQL_PASSWORD contains @

### ISSUE THREAD

**Issue by moisei** [tobybatch/kimai2#97]
**Describe the bug**
```
  DB_TYPE=$(awk -F '[/:@]' '{print $1}' <<< $DATABASE_URL)
  DB_USER=$(awk -F '[/:@]' '{print $4}' <<< $DATABASE_URL)
  DB_PASS=$(awk -F '[/:@]' '{print $5}' <<< $DATABASE_URL)
  DB_HOST=$(awk -F '[/:@]' '{print $6}' <<< $DATABASE_URL)
  DB_BASE=$(awk -F '[/:@]' '{print $7}' <<< $DATABASE_URL)
```
This code doesn't work correctly if DATABASE_URL contains @. In my case it failed because of the MYSQL_PASSWORD. Once I've changed the password, the issue disappeared.

**Comment by tobybatch** [comment]
I guess I can add this as a feature request and just Document it for now.
