### ISSUE TITLE
Usage of postfix container

### ISSUE THREAD

**Issue by jokay** [tobybatch/kimai2#99]
Is the usage of the container [catatnight/postfix](https://hub.docker.com/r/catatnight/postfix) with a 6 year old [code base](https://github.com/catatnight/docker-postfix) in your [docker-compose.yml](https://github.com/tobybatch/kimai2/blob/master/docker-compose.yml#L59) still a good idea and advisable?

**Comment by tobybatch** [comment]
I don't know.  It just sends email, and it works.  It's not exposed outside the docker-compose network.  I guess it could be changed do you have a preferred image?

**Comment by jokay** [comment]
Not really :wink: but I may give it a try without it as I won't send any emails in my setup.

**Comment by tobybatch** [comment]
Then just comment it out, it's not needed.
